Makefile

The fix for the `GHSA-hcpj-qp55-gfph` CVE is now [released](https://github.com/gitpython-developers/GitPython/issues/1515#issuecomment-1367120052). `pip-audit` doesn't need to exclude it anymore. 

chore(deps): use the fix for GHSA-hcpj-qp55-gfph

---

.github/dependabot.yaml

chore(deps): enable Dependabot to check Go deps

---

scripts/dev_scripts/copyright-checker.sh

chore: update the copyright header at a specific line

---

Makefile
scripts/dev_scripts/copyright-checker.sh

To make it easier to download and install binaries that are not tracked by package managers, this PR adds a separate target to the `Makefile` (`setup-binaries`), which can be directly used for example in a `Dockerfile`.
Note that if the corresponding files exist, we won't try to download and install. In that case, to force download and install we can use `make clean setup-binaries` or `make nuke setup-binaries`.
This would help managing `slsa-verifier` until we have a better solution: see #16.

build: add separate target to setup binaries

---

.pre-commit-config.yaml
go.mod
go.sum
tests/e2e/configurations/micronaut_core_config.yaml
tests/e2e/expected_results/micronaut-core/micronaut-core.json

Upgrades pre-commit hooks, in particular `isort`, to fix the broken poetry upgrade [issue](https://github.com/PyCQA/isort/pull/2078).
This PR also upgrades the Go dependencies, which haven't been picked up by Dependabot yet.

chore(deps): update pre-commit hooks and go deps

---

Makefile
pyproject.toml

This PR updates `cyclonedx-bom` Python module and uses `cyclonedx-py` instead of the deprecated `cyclonedx-bom` CLI command.
For more information see: https://github.com/CycloneDX/cyclonedx-python/releases/tag/v3.11.0.

chore(deps): update cyclonedx-bom and remove deprecated CLI command

---

.github/workflows/codeql-analysis.yaml

[Scorecards](https://github.com/ossf/scorecard) lowers the score if a commit is not analyzed by CodeQL. We had initially added filters to avoid running CodeQL unnecessarily, e.g., on `*.md` files, but to follow Scorecards recommendations this PR removes the filtering.

ci: enable CodeQL for all files

---

src/macaron/slsa_analyzer/build_tool/base_build_tool.py

Following the [conversation here](https://github.com/oracle-samples/macaron/pull/67#discussion_r1149903666), this PR improves path comparison for build directory detection.

chore: improve path comparison in build dir detection

---

.github/workflows/release.yaml

Based on Scorecard report we should avoid `downloadThenRun` patterns because we won't have a chance to review the download script before running it.
Also see this [discussion](https://serverfault.com/questions/226386/wget-a-script-and-run-it/890417).

fix: do not use download script for Syft

---

scripts/dev_scripts/integration_tests.sh
src/macaron/slsa_analyzer/analyzer.py
src/macaron/slsa_analyzer/git_url.py

fix: do not pull the latest when analyzing a target with local repo path

---

Makefile
docker/Dockerfile.base
docker/Dockerfile.final

chore: update Souffle to version 2.4

---

src/macaron/slsa_analyzer/registry.py

fix: restore the runner if an uncaught exception happens in a check (#132)

---

src/macaron/output_reporter/results.py
src/macaron/slsa_analyzer/analyzer.py

This PR uses the result record ID  instead of the remote path as  identifier to prevent adding duplicate dependencies for same artifacts. 
Closes #227

chore: do not add a duplicate dependency to result record

---

pyproject.toml

This PR upgrades `requests` dependency to `2.31.0` to fix `CVE-2023-32681`.
See https://github.com/psf/requests/releases/tag/v2.31.0.

fix: upgrade requests to 2.31.0 to fix CVE-2023-32681

---

src/macaron/slsa_analyzer/registry.py

fix: do not overwrite an existing check relationship when a check has no parent in the Registry

---

.github/workflows/release.yaml
Makefile
pyproject.toml

Originally `commitizen` was installed individually for performance reasons. However, this meant that we had to always manually update `commitizen` in the GitHub Action. This PR runs `make setup` to install `commitizen`, which means installing all the packages but on the plus side we won't have to worry about updating it manually anymore.

build: use make setup install commitizen

---

.github/workflows/_generate-rebase.yaml
.github/workflows/release.yaml

As part of the automatic release, a bump commit will be pushed to `main` after the PR from `staging` to `main` is merged. This PR adds a workflow that automatically rebases `staging` on `main` to ensure they are synchronized.

ci: add a workflow to rebase staging on main after release

---

.github/workflows/_deploy-github-pages.yaml
.github/workflows/release.yaml

Closes #248 
By running this reusable workflow, the documentations will be published at https://oracle-samples.github.io/macaron/.

ci(deploy): add a workflow to deploy docs to GitHub pages

---

.github/workflows/release.yaml

feat(release): generate SLSA provenance for the Docker image

---

.github/workflows/_build_docker.yaml
.github/workflows/build_base_image.yaml

Because these GitHub Actions did not have the latest version tags, Dependabot had failed to correctly update the version tags in comments.

chore(deps): fix actions/checkout versions in comments

---

src/macaron/__main__.py
src/macaron/policy_engine/policy_engine.py

**Description**
I fixed issue #250 by assigning both `--file` and `--show-prelude` flags in the `verify-policy` action command to a mutual exclusive group.
This will effective only allow the user to use either `--file` or `--show-prelude` at one time.
I also refactored the code to generate the prelude from a database to a different method rather than putting it inside the same method used for running the policy engine against the policy file provided in `--file`.

chore: remove running the policy engine when --show-prelude is provided

---

.github/workflows/release.yaml

Unfortunately, we need approval for running SLSA provenance genrator's third-party GitHub Actions. We disable provenance generation until this issue is resolved: https://github.com/slsa-framework/slsa-github-generator/issues/2204.

fix(release): disable SLSA provenance for now

---

CONTRIBUTING.md
README.md
docs/README.md

docs: adjust README.md and CONTRIBUTING.md

---

Makefile

This PR improves the `docs` target in the `Makefile` to check for changes in `rst` source files.

build(docs): check changes to rst files in Makefile

---

docs/source/pages/output_files.rst
docs/source/pages/using.rst

docs: update the Output Files Guide page in the Sphinx documentation

---

scripts/dev_scripts/integration_tests.sh
src/macaron/dependency_analyzer/cyclonedx_mvn.py
src/macaron/slsa_analyzer/analyze_context.py
src/macaron/slsa_analyzer/analyzer.py
src/macaron/slsa_analyzer/build_tool/base_build_tool.py
src/macaron/slsa_analyzer/checks/build_as_code_check.py
src/macaron/slsa_analyzer/checks/build_script_check.py
src/macaron/slsa_analyzer/checks/build_service_check.py
src/macaron/slsa_analyzer/specs/build_spec.py
tests/dependency_analyzer/expected_results/cyclonedx_timyarkov_multibuild_test.json
tests/e2e/expected_results/multibuild_test/multibuild_test.json
tests/slsa_analyzer/checks/test_build_as_code_check.py
tests/slsa_analyzer/checks/test_build_script_check.py
tests/slsa_analyzer/checks/test_build_service_check.py
tests/slsa_analyzer/checks/test_vcs_check.py

Basic multiple build tool detection (essentially converting the tool part of BuildSpec to a list)
TODO before final PR:
- Double triple check nothing was missed
- Rebase to staging (+squash commits)
- Update unit tests to multi-build tool
- Do general system testing to see if everything works as expected (did very quick test and at the very least it doesn't crash when ran on https://github.com/timyarkov/GuardianEmailClient)

feat: multi build tool detection

---

scripts/dev_scripts/integration_tests.sh
scripts/release_scripts/run_macaron.sh
src/macaron/__main__.py
src/macaron/config/defaults.ini
src/macaron/errors.py
src/macaron/slsa_analyzer/analyzer.py
src/macaron/slsa_analyzer/git_service/__init__.py
src/macaron/slsa_analyzer/git_service/base_git_service.py
src/macaron/slsa_analyzer/git_service/bitbucket.py
src/macaron/slsa_analyzer/git_service/github.py
src/macaron/slsa_analyzer/git_service/gitlab.py
src/macaron/slsa_analyzer/git_url.py
tests/e2e/expected_results/tinyMediaManager/tinyMediaManager.json
tests/slsa_analyzer/git_service/test_github.py
tests/slsa_analyzer/git_service/test_gitlab.py
tests/slsa_analyzer/test_git_url.py

Closes #301.
This PR adds support for cloning GitLab repositories in Macaron. Specifically, GitLab repositories can now be cloned as either main targets or dependencies in a `macaron analyze` run.
This feature comes with the following additions/changes:
* The old `[git]` section in the `.ini` configuration will now be replaced by the new `[git_service.*]`  sections.
* Each `[git_service]` section corresponds to a different git service with a `domain` key. This domain is used to determine if a Git service hosts a repo given the repo's Git URL.
* If the `domain` key is not found in any `[git_service.*]`  section, the command `macaron analyze`  will error right away before any analysis is done.
* Users can configure 2 different GitLab services in the `[git_service.gitlab.*]`  sections: a …

feat: add support for cloning GitLab repositories

---

src/macaron/dependency_analyzer/cyclonedx.py

Sometimes SBOMs miss certain elements, such as `metadata.component`, which can throw `AttributeError` exception when `get` is called on the element if it is `None`, e.g., 
```python
bom.get("metadata").get("component").get("bom-ref")
```
On the other hand, because we use the `get` method, `KeyError` is never raised. See the documentation [here](https://docs.python.org/3/library/stdtypes.html#dict.get).

chore: catch AttributeError exception while processing SBOM

---

docs/source/pages/cli_usage/action_dump_defaults.rst
docs/source/pages/using.rst

Adds instructions for using the repo finder feature to the "using" docs page.

docs: add instructions on using repo finder

---

scripts/release_scripts/run_macaron.sh
src/macaron/config/defaults.ini
src/macaron/slsa_analyzer/analyzer.py
src/macaron/slsa_analyzer/git_service/__init__.py
src/macaron/slsa_analyzer/git_service/gitlab.py
src/macaron/slsa_analyzer/git_url.py
tests/slsa_analyzer/git_service/test_gitlab.py
tests/slsa_analyzer/test_git_url.py

This PR is to do the following tasks:

chore: remove logging in clone_remote_repo function

---

src/macaron/dependency_analyzer/java_repo_finder.py
tests/dependency_analyzer/java_repo_finder/resources/example_pom.xml
tests/dependency_analyzer/java_repo_finder/test_java_repo_finder.py

This is a small extension to the repo finding feature. It exists to provide support for Maven properties found within SCM metadata. These are of the form: ${property}
Maven provides five ways in which these property values can be used. See https://maven.apache.org/pom.html
We support only the two where the property references another tag within the same POM file. No attempt is made to resolve properties that reference external values such as environmental variables, Java properties, etc.

feat: resolve Maven properties in found POMs

---

src/macaron/errors.py
src/macaron/slsa_analyzer/analyzer.py
src/macaron/slsa_analyzer/git_service/base_git_service.py
src/macaron/slsa_analyzer/git_service/bitbucket.py
src/macaron/slsa_analyzer/git_service/github.py
src/macaron/slsa_analyzer/git_service/gitlab.py
tests/slsa_analyzer/git_service/resources/self_hosted_gitlab_repo/test.txt
tests/slsa_analyzer/git_service/test_gitlab.py

This PR does the following tasks:
- For GitLab repositories, after we **freshly clone** the repo, we update the origin remote URL with the original non-token URL instead of the token-embedded URL. If a GitLab repository is already cloned, we don't do anything.
- Bring the logic to checkout specific branch/commit inside GitService class to properly handle the remote URL (used for fetching) in each repository.
- For GitLab repositories: It enables us to revert the origin remote URL back to the token-embedded URL to allow fetching new changes from remote. At the end of the checkout operation, the remote origin URL is once again updated to its original non-token URL. 
TODO:

chore: update gitlab repo remote url

---

pyproject.toml

See https://docs.pytest.org/en/latest/how-to/failures.html#warning-about-unraisable-exceptions-and-unhandled-thread-exceptions
Unraisable exceptions and unhandled thread exceptions are normally considered bugs, but may go unnoticed because they don’t cause the program itself to crash. Pytest detects these conditions and issues a warning that is visible in the test run summary. This PR changes the warnings to errors instead.

test: fail on unraisable exceptions

---

docs/source/conf.py
src/macaron/parsers/bashparser.py
src/macaron/slsa_analyzer/checks/build_as_code_check.py
src/macaron/slsa_analyzer/checks/provenance_l3_check.py
src/macaron/slsa_analyzer/database_store.py
tests/slsa_analyzer/checks/base_check/test_base_check.py

This PR addresses the `flake8` and `black` issues [raised](https://github.com/oracle/macaron/pull/360) after updating `pre-commit` tools.

chore: fix black and flake8 issues for the new versions of the tools

---

src/macaron/slsa_analyzer/checks/provenance_l3_check.py
src/macaron/util.py

The paths in an archive file are checked for path traversal patterns before extraction. Also, Bandit v1.7.5 is producing false positives for request timeout arguments, which have been suppressed.
These issues were [raised](https://github.com/oracle/macaron/pull/360) after updating `pre-commit` tools.
Note that I still need to suppress `B202:tarfile_unsafe_members` because Bandit has a [bug](https://github.com/PyCQA/bandit/issues/1038) for this check.

fix: check paths in an archive file before extracting

---

docs/source/pages/using.rst
src/macaron/config/defaults.ini

docs: add instructions for analyzing GitLab repositories

---

docs/source/conf.py
docs/source/pages/apidoc/macaron.code_analyzer.rst
docs/source/pages/apidoc/macaron.config.rst
docs/source/pages/apidoc/macaron.database.rst
docs/source/pages/apidoc/macaron.dependency_analyzer.rst
docs/source/pages/apidoc/macaron.output_reporter.rst
docs/source/pages/apidoc/macaron.parsers.rst
docs/source/pages/apidoc/macaron.parsers.yaml.rst
docs/source/pages/apidoc/macaron.policy_engine.rst
docs/source/pages/apidoc/macaron.rst
docs/source/pages/apidoc/macaron.slsa_analyzer.build_tool.rst
docs/source/pages/apidoc/macaron.slsa_analyzer.checks.rst
docs/source/pages/apidoc/macaron.slsa_analyzer.ci_service.rst
docs/source/pages/apidoc/macaron.slsa_analyzer.git_service.rst
docs/source/pages/apidoc/macaron.slsa_analyzer.provenance.expectations.cue.rst
docs/source/pages/apidoc/macaron.slsa_analyzer.provenance.expectations.rst
docs/source/pages/apidoc/macaron.slsa_analyzer.provenance.rst
docs/source/pages/apidoc/macaron.slsa_analyzer.rst
docs/source/pages/apidoc/macaron.slsa_analyzer.specs.rst
src/macaron/database/table_definitions.py
src/macaron/slsa_analyzer/provenance/expectations/__init__.py
src/macaron/slsa_analyzer/provenance/expectations/cue/__init__.py

We should not manually modify the automatically generated rst files. Otherwise, generating documentation using docstrings gets very tricky. This changeset also adds missing `__init__.py` modules due to which a warning was raised by Sphinx.

docs: remove manual modifications to generated rst files

---

.flake8
pyproject.toml

Currently `pylint` and `flake8` check line lenghts in different ways, so this change disables `pylint` and `flake8`’s default checkers and uses Bugbear only (which is a little more lenient anyway, see [here](https://github.com/PyCQA/flake8-bugbear#list-of-warnings)).

ci: make line-length checks a bit more tolerant using Bugbear only

---

src/macaron/database/rfc3339_datetime.py

Fixes https://github.com/oracle/macaron/issues/378
The existing code doesn’t ensure that the serialized object is a `datetime` and it always coerces the timezone to UTC; the docstring seems to indicate that serialized `datetime` objects are stored as “[naive](https://docs.python.org/3/library/datetime.html#aware-and-naive-objects)” strings but that’s not the case because `Z` is appended to the serialized string which indicated [Zulu](https://en.wikipedia.org/wiki/ISO_8601#Coordinated_Universal_Time_(UTC)) time (GMT).
This change preserves the timezone of the serialized `datetime` objects, and adds UTC for naive `datetime` objects before serializing to string. Always deserializes to the original timezone.

fix(orm): serialize datetime object’s timezone instead of always coercing to UTC when persisting to the SQLite db

---

Makefile

We need to manage Go dependencies differently from Python ones because the pinned Go dependencies are checked into the repository and any dependency update can result in a code change, polluting other code changes.
With this PR, the Go dependencies will only be upgraded by Dependabot and ``make upgrade-go`` should be used directly if a manual upgrade is required.

build: do not update Go dependencies in Makefile setup

---

Makefile

Looks like `pip-audit` [is not ](https://github.com/oracle/macaron/actions/runs/5888771799/job/15970639825?pr=409) recognizing `PYSEC-2023-137` as an alias for `GHSA-pr76-5cm5-w9cj`. Switching to `CVE-2023-40267` ID instead which is recognized by `pip-audit`.
Missing alias for `GHSA-pr76-5cm5-w9cj` in `PYSEC-2023-137`: https://github.com/pypa/advisory-database/issues/142
GitHub Advisory: https://github.com/advisories/GHSA-pr76-5cm5-w9cj
PYSEC Advisory: https://github.com/pypa/advisory-database/blob/a3bd5be966a999b065ac798d13795760c2e13d43/vulns/gitpython/PYSEC-2023-137.yaml
Note: even though Macaron uses PyDriller and GitPython, it is not vulnerable to this CVE because it does not set the [`allow_unsafe_options`](https://github.com/gitpython-developers/GitPython/commit/ca965ecc81853bca7675 …

chore(deps): use CVE-2023-40267 alias for the audit check

---

src/macaron/slsa_analyzer/checks/build_as_code_check.py
src/macaron/slsa_analyzer/checks/build_service_check.py
tests/e2e/expected_results/multibuild_test/multibuild_test.json
tests/slsa_analyzer/checks/test_build_as_code_check.py
tests/slsa_analyzer/checks/test_build_service_check.py

Right now while projects with multiple build tools are analysed properly, the justifications in the report don't reflect all build tools used due to logic that short-circuits the `build_as_code` and `build_service` checks upon a single tool passing. This is a problem when testing for if certain build tools get picked up in scenarios of multiple other build tools being present, since there is a chance it likely won't get reflected in the report, thus making it difficult to properly test such cases.
- `build_as_code_check.py` and `build_service_check.py` now perform their checks for every single build tool, regardless of if there's a pass or not (still preserving previous one pass = check passed logic however)
- Results for analysis of https://github.com/timyarkov/multibuild_test updated to …

fix: update justifications to be complete for multi build tool projects

---

src/macaron/config/defaults.ini

The SLSA GitHub Generator repository hosts new trusted builders:
* Maven and Gradle since v1.9.0
* Node.js since v1.6.0
* Container-based since v1.7.0
This PR adds the corresponding reusable workflows to the trusted builders in Macaron.
See https://github.com/slsa-framework/slsa-github-generator/tree/main#builders

feat: support trusted SLSA L3 builders for Maven, Gradle, Node.js, and containers

---

docker/Dockerfile.final
docker/user.sh
docs/source/pages/installation.rst
scripts/release_scripts/run_macaron.sh

Maven and Gradle do not use the systems proxy settings and support custom files `~/.m2/settings.xml` and `~/.gradle/gradle.properties` or other mechanisms for proxy configuration.
This PR uses the global settings files from the host machine to setup the proxy for Maven and Gradle in the Docker container.

fix(proxy): use the host proxy settings for Maven and Gradle

---

Makefile

This PR adds `CVE-2023-40590` to `pip-audit`'s ignore list until it is resolved. Macaron does not support Windows systems, so it is not affected. See https://github.com/gitpython-developers/GitPython/security/advisories/GHSA-wfm5-v35h-vwf4
This PR also removes CVE-2023-40267 from the ignored CVEs because PyDriller 2.5.1 no longer pins GitPython to the vulnerable version. See https://github.com/ishepard/pydriller/issues/280

chore(deps): address pip-audit reports

---

Makefile

This PR adds CVE-2023-41040 reported against GitPython 3.1.32 to the ignore list until the patch is out.
Note that Macaron is not affected by this CVE because it does not call the problematic functions like `commit` and sanitizes arguments before calling GitPython APIs.
See: https://osv.dev/vulnerability/GHSA-cwvm-v4w8-q58c

chore(deps): address pip-audit report for CVE-2023-41040

---

.github/workflows/_build_docker.yaml
docs/source/pages/cli_usage/index.rst
docs/source/pages/installation.rst
scripts/release_scripts/run_macaron.sh

Closes #438
By default, always pull latest version of docker image, but allow this behaviour to be overidden by setting the DOCKER_PULL env var.

fix: always pull latest docker image in run_macaron.sh

---

docs/source/pages/using.rst
src/macaron/config/defaults.ini
src/macaron/slsa_analyzer/analyzer.py
src/macaron/slsa_analyzer/git_service/base_git_service.py
src/macaron/slsa_analyzer/git_service/github.py
src/macaron/slsa_analyzer/git_service/gitlab.py
src/macaron/slsa_analyzer/git_url.py
tests/slsa_analyzer/git_service/test_gitlab.py
tests/slsa_analyzer/test_git_url.py

Closes #416.
Rename the attribute `domain` to `hostname` in Git service sections in Macaron's `.ini` config.

fix: rename `domain` to `hostname` in Git service configuration

---

tests/e2e/expected_results/micronaut-core/micronaut-core.json

The provenance generation on [micronaut-core](https://github.com/micronaut-projects/micronaut-core/actions/runs/6039112753/job/16391009301) repository has failed after [updating](https://github.com/micronaut-projects/micronaut-core/actions/runs/6039112753/workflow#L137).
Looking into the logs, it fails at this [step](https://github.com/micronaut-projects/micronaut-core/actions/runs/6039112753/job/16390907246#step:6:265) while creating the verifier, which seems to be a transient network issue.
This PR updates the expected results for `micronaut-core` and allows the provenance-related checks fail until the issue is resolved.

ci(integration-tests): allow provenance checks fail on micronaut-core temporarily

---

src/macaron/config/defaults.ini
src/macaron/slsa_analyzer/build_tool/base_build_tool.py
src/macaron/slsa_analyzer/build_tool/gradle.py
tests/slsa_analyzer/build_tool/test_gradle.py

This PR sets a timeout on the `subprocess.run()` call that runs `gradlew properties` to detect the group ID of a Gradle project. The `timout` is read from `build_timeout` in `defaults.ini` for the detected build tool.

fix: add timeout to Gradle Group ID detection

---

scripts/dev_scripts/integration_tests.sh
src/macaron/config/defaults.ini
src/macaron/slsa_analyzer/build_tool/__init__.py
src/macaron/slsa_analyzer/build_tool/docker.py
tests/conftest.py
tests/e2e/expected_results/docker_test/docker_test.json
tests/slsa_analyzer/build_tool/__snapshots__/test_docker.ambr
tests/slsa_analyzer/build_tool/mock_repos/docker_repos/nested_dockerfile/project/Dockerfile
tests/slsa_analyzer/build_tool/mock_repos/docker_repos/no_docker/dummy_file.txt
tests/slsa_analyzer/build_tool/mock_repos/docker_repos/root_dockerfile/Dockerfile
tests/slsa_analyzer/build_tool/mock_repos/docker_repos/root_dockerfile_wildcard/Dockerfile.final
tests/slsa_analyzer/build_tool/mock_repos/docker_repos/root_wildcard_dockerfile/final.Dockerfile
tests/slsa_analyzer/build_tool/test_docker.py

This PR adds support for the detection of Dockerfiles, so as to cover scenarios where Docker gets used as a build tool, e.g. when Macaron gets built using its Dockerfile.
- Docker presence is detected by finding files either named `Dockerfile` or in the formats `*.Dockerfile` or `Dockerfile.*` to cover different naming conventions of dockerfiles, e.g. `dev.Dockerfile` or like Macaron's own `Dockerfile.base` and `Dockerfile.final`. This is defined in `defaults.ini` under `[builder.docker]`
- The supported build command keyword is `build`, and supported deploy command keyword is `push`, defined in `defaults.ini` under `[builder.docker]`
- For CI deploy commands the Github action [docker/build-push-action@v4](https://github.com/docker/build-push-action) is supported, defined in …

feat: add docker build detection

---

Makefile
scripts/dev_scripts/integration_tests_docker.sh
scripts/dev_scripts/test_run_macaron_sh.py
scripts/release_scripts/run_macaron.sh

Closes #460.
* Fix the `run_macaron.sh` script to handle action arguments correctly.
* Add a test script to check for the arguments that are actually passed to the `macaron` command in the Macaron container.

fix: fix `run_macaron.sh` script to handle action arguments correctly

---

src/macaron/database/table_definitions.py

This PR sets ``encode=True`` to encode qualifiers of a PURL string as a normalized string while converting it to a dictionary because SQLite doesn't support ``dict`` type.
It also adds exception handling for deserializing a PURL string while initializing a Component instance.

fix: encode PURL qualifiers as a normalized string

---

src/macaron/slsa_analyzer/checks/provenance_available_check.py
tests/slsa_analyzer/checks/test_provenance_available_check.py

If a repository is not available for an artifact/analysis target identified by a PURL string, the  `mcn_provenance_available_1` check throws an exception. 
This PR fixes this bug by checking if the repository is available before running the check.

fix: check if repository is available in provenance available check

---

src/macaron/policy_engine/prelude/policy.dl
tests/policy_engine/expected_results/policy_report.json
tests/policy_engine/resources/policies/valid/slsa-verifier.dl
tests/policy_engine/test_policy.py

This PR fixes the following bug found as part of integration tests for [this PR,](https://github.com/oracle/macaron/pull/471/files).
Bug description: he policy test failed to apply the policy because it was using the `repo_id` instead the `component_id`, and the related check result could not be found by the policy engine.

fix(policy-engine): use component_id instead of repo_id in policy to find the check result

---

Makefile

GitPython 3.1.35 fixes CVE-2023-40590 and CVE-2023-41040. This PR removes these CVEs from the pip-audit ignore list.
See https://github.com/gitpython-developers/GitPython/releases/tag/3.1.35

chore(deps): remove CVE-2023-40590 and CVE-2023-41040 from the ignore list

---

tests/slsa_analyzer/provenance/expectations/cue/resources/valid_expectations/urllib3_PASS.cue

Closes #479 
Regex value in expectation file is adjusted slightly so as to account for the urllib3 version branch name / tag sometimes starting with a `v`.

test: improve expectation regex value to better match usage in urllib3

---

tests/config/test_defaults.py

I am removing a test that fails in environments where the user running the test actually has write access to the `/` directory.
This may happen in, for example, a test environment inside a container where the user is `root`, which is quite common in CI systems (e.g. [GitLab Runner with docker executor](https://docs.gitlab.com/runner/executors/docker.html), or [Jenkins docker pipelines](https://www.jenkins.io/doc/book/pipeline/docker/)).

test: adjust flaky test which relies on filesystem permissions

---

src/macaron/slsa_analyzer/provenance/intoto/__init__.py

For some reason, `pylint` suddenly started to report the following issue, which is causing our CI to fail.
```
src/macaron/slsa_analyzer/checks/provenance_l3_check.py:360:39: E1136: Value 'provenance_payload.statement' is unsubscriptable (unsubscriptable-object)
```
I am pretty sure this is a false positive. I have simplified the code causing the issue to resolve it.

chore: resolve pylint unsubscriptable object issue

---

src/macaron/util.py

This PR changes the log level for HTTP response errors to the `debug` level and removes the response text from the log, which can be an HTML page sometimes.

chore: do not log failed HTTP response text as error

---

src/macaron/config/defaults.ini
src/macaron/slsa_analyzer/checks/build_as_code_check.py
src/macaron/slsa_analyzer/checks/build_service_check.py
tests/e2e/expected_results/sget/sget.json

This PR adds [changesets/action](https://github.com/changesets/changesets) to the list of GitHub Actions used to publish npm packages. An example project that uses this Action to automate releases is [sigstore/sigstore-js](https://github.com/sigstore/sigstore-js). Note that there is a TODO to also check the `publish` [input](https://github.com/changesets/action#with-publishing) provided to this Action to improve detection accuracy.
This PR also fixes a bug for using the deploy `github_actions` for build tools. Previously, only the `github_actions` of `pip` build tool was read from `defaults.ini` and used in `build_as_code_check.py`. This fix removes this hard-coded read from `defaults.ini` and makes it applicable to all build tools.

chore: add changesets/action for npm release

---

scripts/dev_scripts/integration_tests_docker.sh
scripts/dev_scripts/test_run_macaron_sh.py
tests/dependency_analyzer/compare_dependencies.py
tests/e2e/compare_e2e_result.py
tests/e2e/repo_finder/repo_finder.py
tests/policy_engine/compare_policy_reports.py

This pull request is to ensure we run all dev scripts written in Python with our current development python version 3.11 (as specified in the [`CONTRIBUTING.md`](https://github.com/oracle/macaron/blob/52cecac/CONTRIBUTING.md) file) instead of system Python (`/usr/bin/env python`). This includes:
- Removing all `/usr/bin/env python` shebang from Python scripts.
- Modifying the way these scripts are run in the `integration_test_docker.sh` script.

chore: avoid running python dev scripts with system python

---

docs/source/pages/cli_usage/command_analyze.rst
docs/source/pages/cli_usage/command_dump_defaults.rst
docs/source/pages/cli_usage/command_verify-policy.rst
docs/source/pages/cli_usage/index.rst
docs/source/pages/output_files.rst
docs/source/pages/tutorials/index.rst
docs/source/pages/using.rst
scripts/dev_scripts/test_run_macaron_sh.py
scripts/release_scripts/run_macaron.sh

This pull request makes a number of improvements to our current `run_macaron.sh` script.
This is to prepare for another pull request, #512, which adds support for Podman as an alternative container engine to run the Macaron image.
**Commit**: 95cb003d27dd41287eb78ea20d7f2ac401264551
The following bash built-in flags are added to the script. These flags effectively help make the script less error-prone.
- `set -e`: exit immediately if a command fails (with non-zero return code), or if a function returns non-zero.
- `set -u`: treat unset variables and parameters as errors when performing parameter expansion.
Note: In case a variable `${VAR}` is unset but we still need to expand, we can use the syntax `${VAR:-}` to expand it to an empty string ([bash …

chore: improve the run_macaron.sh script

---

src/macaron/database/table_definitions.py

The `__init__` function in SQAlchemy's `DeclarativeBase` class [does not take](https://github.com/sqlalchemy/sqlalchemy/blob/a342b3d503f968bbf43f3b2de1f4f623b03a6310/lib/sqlalchemy/orm/decl_api.py#L839) positional arguments. The `Repository` ORM mapping however passes `*args` to `DeclarativeBase`, which is not correct. So far we haven't run into any issues because we always pass keyword arguments while initializing `Repository` instances. 
This PR fixes this issue by not passing ` *args` to the parent `DeclarativeBase` class.

chore: do not pass *args to SQLALchemy DeclarativeBase class

---

docs/source/pages/installation.rst
scripts/release_scripts/run_macaron.sh

The bash pattern matching syntax `@(...)` requires the shopt option `extglob` to be set. Although this option is set by default on newer versions of bash, it is not always the case. One known case is on MacOS, where the default bash version is `bash 3.2`. (even on the latest version of MacOS).
Reproduction: Run the following bash script in the `bash:3.2` docker container.
```
#!/usr/bin/env bash
if [[ "${DOCKER_PULL}" != @(always|missing|never) ]]; then
echo "DOCKER_PULL must be one of: always, missing, never (default: always)"
exit 1
fi
```

fix: fix bash syntax error when running `run_macaron.sh` on MacOS

---

src/macaron/slsa_analyzer/git_url.py

Closes #486 
This bug happened because of the way branch check out is handling in this [method](https://github.com/oracle/macaron/blob/71accbf81e849947ca238ebfa3a9a6ef88fd01f6/src/macaron/slsa_analyzer/git_url.py#L65).
At the moment, the process Macaron in which Macaron tries to checkout the correct branch and commit for the analysis is as follows:
- The branch to checkout is either the value provided by the user (via `--branch` in the CLI) or the default branch of the repository ([implementation](https://github.com/oracle/macaron/blob/71accbf81e849947ca238ebfa3a9a6ef88fd01f6/src/macaron/slsa_analyzer/git_url.py#L251)):
- We are using `git rev-parse --abbrev-ref origin/HEAD` to obtain the value `origin/<default_branch_name>` ([references](https://stackoverflow.com/questions/28666357/git-ho …

fix: do not use git set-branches if the target branch is not currently available in the repository

---

src/macaron/slsa_analyzer/ci_service/base_ci_service.py

This PR change the error message printed out [here](https://github.com/oracle/macaron/blob/13206e56463f51ccd98415ec9c249688c70ccdff/src/macaron/slsa_analyzer/ci_service/base_ci_service.py#L167) to a debug message.
This is because in this [method](https://github.com/oracle/macaron/blob/13206e56463f51ccd98415ec9c249688c70ccdff/src/macaron/slsa_analyzer/ci_service/base_ci_service.py#L129), we are trying multiple config file names for a ci service until we find one, so it's not an error if we cannot find a config file. 
For example, if we run Macaron:
```
macaron analyze -purl pkg:maven/org.opentest4j/opentest4j@1.2.0?type=jar --skip-deps
```  
This is the log message if we keep it as an error message
```
...
2023-10-27 10:53:21,731 [INFO] BEGIN CHECK: mcn_build_service_1
2023-10-27 …
```

chore: print debug message if a ci service config file is not found

---

src/macaron/repo_finder/repo_finder.py

When the `purl` string's type, which is provided as input is not a repository, which not log it as an error. This PR changes the log level and improves the log message.

chore: improve the log message in repo finder

---

scripts/release_scripts/run_macaron.sh

This PR adds support for Podman as an alternative container engine to run the Macaron image.
The current `run_macaron.sh` script is not fully compatible with Podman, due to known cases where Docker and Podman behave differently. Changes in this PR address these cases.
Podman completely bans volume-mounting non-existing directories on the host into the container. See https://github.com/containers/podman/issues/6234 for more details.
Meanwhile, mounting a non-existing directory on the host into a container is allowed in Docker. There is a peculiar behavior: the non-existing directory is owned by `root` both inside and outside the container.
**Solution**: Before volume-mounting a directory, we can either (1) create that directory if it does not exist, or (2) error. The choice should be …

fix: resolve podman compatibility issues

---

src/macaron/output_reporter/jinja2_extensions.py
src/macaron/output_reporter/results.py
src/macaron/output_reporter/templates/macaron.html

This Pull request fixes the issues in the HTML report of the main target where the dependencies are all displayed as `AVAILABLE` even though the repository URL is not available for them - see example below:
```shell
macaron analyze -rp https://github.com/apache/maven -sbom test_sbom.json
```
with the content of `test_sbom.json` as follows: [test_sbom.json](https://github.com/oracle/macaron/files/13234713/test_sbom.json)
In this example, Macaron cannot find the repository URL for the dependency component `javax.inject:javax.inject`. However, Macaron still tries to run all checks on that component and produce an "empty" HTML report for it. This is part of the design implemented in this [PR](https://github.com/oracle/macaron/pull/165):
- Macaron still run the checks and produce a HTML report …

chore: display the repository URL status of dependencies in html report instead of the analysis status

---

docs/source/pages/using.rst
src/macaron/slsa_analyzer/analyzer.py
src/macaron/slsa_analyzer/git_url.py

Closes #530 .
This Pull Request addresses the issues described in #530 by doing the following tasks:
- When checkout a branch or a commit, use the `--force` flag of the `git checkout` command to reset the index and working tree, potentially remove any uncommitted changes. For more information on this flag, see [here](https://git-scm.com/docs/git-checkout#Documentation/git-checkout.txt---force).
- Remove the `git_url.reset_git_repo` function which create a stash and reset the index and working tree of the target repository before checking out any branch or commit. 
- Add a warning to the Sphinx documentation for the use case of `Analyzing a locally cloned repository` about Macaron's ability to reset the index and working tree of the target repository.

chore: use --force for running git checkout to prevent issues like #530

---

Makefile
scripts/dev_scripts/integration_tests.sh

This PR aims to provide a way of automatically updating the expected results used by the integration tests, closing #542.
The initial implementation achieves this by replacing all `python` commands with a variable that can be overridden when the integration test script is passed a specific third argument, thereby performing a copy operation on the two file arguments that would otherwise be compared. At the current time, this avoids performing copy operations on other possible `python` commands by relying on the fact that only comparison commands use three arguments, with arguments 2 and 3 being files.
Usage:
1. Run the integration tests as usual.
2. Verify any differences between Macaron output and expected results are legitimate.
3. Run updater to replace outdated expected files. …

test: add update option to integration script

---

docs/Makefile
pyproject.toml

Since this [issue](https://github.com/oracle/macaron/issues/84) in `sphinx-autodoc-typehints` extension is resolved, we don't have any warnings. This PR changes the Sphinx configuration to treat warnings as errors, which helps us to detect documentation issues in CI tests.
This PR also raises the lower bound version of `sphinx-autodoc-typehints` to `1.25.2`, which is currently the latest version, making sure the problematic versions are not used again.

docs: treat Sphinx warnings as erros

---

pyproject.toml
src/macaron/config/defaults.py
src/macaron/output_reporter/jinja2_extensions.py
src/macaron/output_reporter/results.py
src/macaron/policy_engine/souffle_code_generator.py
src/macaron/slsa_analyzer/git_service/api_client.py
src/macaron/slsa_analyzer/git_url.py
src/macaron/slsa_analyzer/registry.py
src/macaron/util.py

While reading through some code, I realized the examples in some docstrings are wrong. These should have been caught by `doctest`.
Currently in `pyproject.toml`, `pytest` is configured as follows:
```toml
[tool.pytest.ini_options]
addopts = "--verbose --doctest-modules -ra --cov macaron"  # Consider adding --pdb
testpaths = [
"tests",
]
```
Although the `--doctest-modules` flag is enabled, meaning `doctest` should run, `testpaths` is limited to only the `tests` directory. This does not allow `doctest` to pick up the docstring examples in `src/macaron`.
In this PR, I enable `doctest` to discover docstring examples in `src/macaron` as follows:
```diff
testpaths = [
+   "src/macaron",  # this is included to run doctest on examples
"tests",
]
```
I also fix cases where the example fails …

chore: resolve doctest issues

---

.pre-commit-config.yaml
src/macaron/slsa_analyzer/analyze_context.py

This PR updates the `pre-commit` hooks. As part of this update, the  `commitizen` version `3.5.2`, which is causing [this failure](https://github.com/oracle/macaron/actions/runs/7085677573/job/19282408488?pr=562#step:8:21) in the CI is updated to the latest version. This will fix the CI failures. 
This PR also adds the change made by `pyupgrade` after updating the `pre-commit` hook.

chore(deps-dev): update pre-commit hooks

---

scripts/dev_scripts/integration_tests.sh

Closes #577 
This PR fixes the description of test for `micronaut-test` and also removes the test that uses PURL `pkg:maven/io.micronaut/micronaut-test-core@4.1.0` because for some reason this artifact is not published on Maven central. This test should have been failing but we were checking the wrong output file.

ci(test): fix the test descriptions and comparison for micronaut-test

---

scripts/dev_scripts/integration_tests.sh

Moving the return code check in the integration test script to the end.
Previously, when there was an error in the last two cases, the script would not exit with non-zero code.

chore: move return code check in integration test script to the end

---

tests/slsa_analyzer/ci_service/test_github_actions.py

This PR fixes a bug in the GitHub Actions workflow detection test. The assertions in the `test_get_workflows` function were checking the return values of `list.sort()`, which is an in-place function and doesn't return anything. Instead we should compare the sorted lists.
This PR also removes `MacaronTestCase`, which is not necessary anymore.

test: fix the GitHub Actions workflow detection test

---

scripts/dev_scripts/integration_tests.sh
src/macaron/repo_finder/commit_finder.py
src/macaron/slsa_analyzer/analyzer.py
tests/e2e/expected_results/maven/guava.json
tests/e2e/expected_results/purl/com_google_guava/guava/guava.json
tests/repo_finder/test_commit_finder.py

As in some cases the branch for a commit found by the commit finder cannot also be found, and that branches are not needed to pull a commit, this PR removes all attempts at retrieving branch information as part of the commit finding process. This makes the commit finder return only a commit hash/digest.
Closes #585

chore: disregard branch in commit finder

---

src/macaron/config/defaults.ini

This PR adds `tox` as a tool to publish artifacts for Python packages.

feat: support tox to publish artifacts to PyPI

---

tests/vsa/compare_vsa.py

This PR fixes an issue in the VSA comparison integration test. We should not compare Macaron version against the snapshot test VSA because the test will fail once we bump the Macaron version in the next release, failing the automatic release altogether!

test(integration): skip comparing Macaron version in VSA test

---

.pre-commit-config.yaml
CONTRIBUTING.md
pyproject.toml
src/macaron/config/defaults.py

This PR 
- moves the configuration to find files for doctests to `.pre-commit-config.yaml` to be consistent with the rest of the hooks.
- It also adds an example doctest for contributors.
- Removes an unnecessary comment in a docstring.

test(docs): improve the doctest configuration

---

scripts/release_scripts/run_macaron.sh
src/macaron/__main__.py
src/macaron/config/global_config.py
src/macaron/slsa_analyzer/git_service/gitlab.py
tests/slsa_analyzer/git_service/test_gitlab.py

Changes the way in which the GitHub token is input into Macaron.

chore: improve token import

---

src/macaron/slsa_analyzer/checks/build_as_code_check.py
src/macaron/slsa_analyzer/checks/build_service_check.py

Record build command in build service check, and change encoding of build/deploy commands in build as code and build service checks to json to make it easier to parse later.

chore: improve build command output

---

docs/source/pages/using.rst
scripts/dev_scripts/integration_tests.sh
src/macaron/__main__.py
tests/e2e/expected_results/purl/org_tinymediamanager/tinyMediaManager.json

For cases where the user has provided a PURL with a version but no repository can be found, this PR allows the analysis to succeed as long as the user provides a repository path as well. This differs from the current functionality where if both a PURL and repo are provided, a commit must be too.
An example of this new use case is added in the integration tests:
`macaron analyze -purl pkg:maven/org.tinymediamanager/tinyMediaManager@4.3.13 -rp https://gitlab.com/tinyMediaManager/tinyMediaManager`
Without this new functionality, the above test would fail as the provided version cannot be found by the Repo Finder.
Closes #621

feat: use repository url provided as input for finding a commit

---

docs/source/pages/using.rst
src/macaron/config/defaults.ini
src/macaron/repo_finder/repo_finder.py
src/macaron/repo_finder/repo_validator.py
src/macaron/slsa_analyzer/git_url.py
src/macaron/util.py
tests/dependency_analyzer/cyclonedx/__snapshots__/test_cyclonedx.ambr
tests/dependency_analyzer/expected_results/cyclonedx_apache_maven.json
tests/slsa_analyzer/test_git_url.py

This PR allows the Repo Finder to return GitHub, etc. URLs that are initially presented as a redirect URL. URLs that can be considered valid redirects are included within a list in the defaults configuration file. URLs found from redirects are validated as per any other URL. A flag is used to prevent infinite redirect loop shenanigans.
Closes #626

feat: follow indirect repository URLs

---

src/macaron/repo_finder/repo_validator.py
tests/e2e/repo_finder/repo_finder.py

This PR updates the Repo Finder e2e test to support the changes made by the new indirect Apache URL support feature.
Closes #642

chore: update repo finder e2e test

---

tests/repo_finder/test_commit_finder.py
tests/slsa_analyzer/mock_git_utils.py

Improves a unit test that fails on my machine.
The test fails due to the assumption that `git init` always initializes a repo with the branch `master`. Meanwhile, the git `defaultBranch` configured on my machine is not `master`. I think this git config is quite common since GitHub now defaults to `main` as the main branch.
I also reckon if the test is based on the precondition of "the repo should have a `master` branch", then it'd better be stated explicitly. This fix tries to achieve that.

chore: explicitly git init with the `master` branch in tests requiring it

---

docs/source/pages/cli_usage/command_analyze.rst
scripts/dev_scripts/integration_tests.sh
src/macaron/__main__.py
src/macaron/slsa_analyzer/analyze_context.py
src/macaron/slsa_analyzer/analyzer.py

Closes #34 .
This PR includes the following additions:
- A CLI option `--provenance-file` is added to received the provenance path from the user.
- The provenance content is loaded using the existing [load_provenance_payload](https://github.com/oracle/macaron/blob/023c6acc63e2023c14b046644cd86ab00151f69f/src/macaron/slsa_analyzer/provenance/loader.py#L74) method. 
- The provenance payload is stored within the AnalyzeContext that we generate from the main software component.
This PR **does not** implements the validation and extracting information from the provenances. That will be added within https://github.com/oracle/macaron/pull/653.

chore: add provenance as an input CLI option

---

src/macaron/slsa_analyzer/package_registry/npm_registry.py
src/macaron/slsa_analyzer/provenance/intoto/__init__.py
src/macaron/slsa_analyzer/provenance/intoto/v01/__init__.py
src/macaron/slsa_analyzer/provenance/intoto/v1/__init__.py
tests/slsa_analyzer/package_registry/test_npm_registry.py
tests/slsa_analyzer/provenance/intoto/v1/__init__.py
tests/slsa_analyzer/provenance/intoto/v1/test_validate.py

This PR adds:
- Support for downloading SLSA v1 provenance files for NPM packages
- Support for v1 in-toto attestation files, including content validation
It also removes comments relating to intended use of the in-toto attestation library after the investigation reported in #426 
Closes #549

feat: discover slsa v1 provenances for npm packages

---

src/macaron/config/defaults.ini
src/macaron/repo_finder/repo_finder_java.py
src/macaron/repo_finder/repo_validator.py
tests/repo_finder/test_repo_finder.py

This PR makes the configuration property `repo_pom_paths` a priority list. When the Repo Finder is resolving URLs to repositories, the first valid URL (based on the ordering of the `repo_pom_paths`) will be returned. By default, the highest priority SCM entry in a POM should be `url`, as this most reliably represents the URL of the source repository.
Closes #640

chore: use priority ordering in java repo finder

---

CONTRIBUTING.md

docs: improve the signing and PR contribution instructions

---

src/macaron/config/defaults.py
src/macaron/repo_finder/repo_finder_java.py
src/macaron/slsa_analyzer/registry.py
tests/config/test_defaults.py

This PR is created to addressed to issue mentioned here https://github.com/oracle/macaron/pull/641#issuecomment-1960742681.
This issue is addressed by removing the parameter `duplicate_ok` in the `get_list` method https://github.com/oracle/macaron/blob/023e0952a2c885b8e31a813b32c1274d210d5629/src/macaron/config/defaults.py#L18-L26. This essentially will make the `get_list` method not modifying the order of elements in the return list of strings. 
As a result, the unit tests in [tests/config/test_defaults.py](https://github.com/oracle/macaron/blob/fb302eba14bf5eab637d788c28dfa1cd492ef890/tests/config/test_defaults.py) are also re-implemented to reflect this new behavior, hence a major modification within that file. 
In additions, I have also rename the parameter `item` to `option` …

fix: preserve the order of elements of the list extract from defaults.ini

---

scripts/dev_scripts/integration_tests.sh
src/macaron/__main__.py
src/macaron/errors.py
src/macaron/json_tools.py
src/macaron/repo_finder/provenance_extractor.py
src/macaron/repo_finder/provenance_finder.py
src/macaron/repo_finder/repo_finder.py
src/macaron/slsa_analyzer/analyzer.py
src/macaron/slsa_analyzer/package_registry/npm_registry.py
src/macaron/slsa_analyzer/provenance/intoto/v01/__init__.py
src/macaron/slsa_analyzer/provenance/intoto/v1/__init__.py
src/macaron/slsa_analyzer/provenance/witness/__init__.py
tests/e2e/defaults/disable_repo_finder.ini
tests/e2e/expected_results/purl/npm/semver/semver.json
tests/repo_finder/test_provenance_extractor.py
tests/repo_finder/test_repo_finder.py
tests/slsa_analyzer/test_analyzer.py

This PR uses provenance files to find commits and repositories for analysis targets.
Provenance can be discovered as followed:
- In a user defined JFrog repository, for Gradle and Maven targets.
- From npm, for npm libraries built with provenance.
- From the user, if provided as a CLI parameter.
The supported provenance types are SLSA v0.1, v0.2, and v1, Witness v0.1. Supported payloads are in-toto v0.1 and v1.

feat: use provenance to find commits for supported PURL types.

---

src/macaron/repo_finder/repo_finder.py
src/macaron/slsa_analyzer/analyzer.py

The `PackageURL` class implements the [`__str__()`](https://docs.python.org/3/reference/datamodel.html#object.__str__) function [here](https://github.com/package-url/packageurl-python/blob/ef3747a2e6c136f3fbe1742c81d6da295cee4546/src/packageurl/__init__.py#L416-L417):
```python
def __str__(self, *args: Any, **kwargs: Any) -> str:
return self.to_string()
```
That `__str__()` function is invoked automatically when using `%s` in a format string (as is the case when logging, [docs](https://docs.python.org/3/library/string.html#format-specification-mini-language)) or when calling the [str()](https://docs.python.org/3/library/stdtypes.html#str) built-in.
This change removes the `to_string()` use such that the plain `PackageURL` objects are passed to logging and `str()` and thereby their …

chore: use dunder function __str__ when requiring a string serialization of a PackageURL object

---

src/macaron/repo_finder/repo_finder_deps_dev.py

This PR simplifies code in the `DepsDevRepoFinder` class thanks to the changes made to the API as part of a new `deps.dev` release. Previously, each language (Python, Rust, C#, and JavaScript) had to follow specific rules to allow for the API to handle each of them. Now, the PURL itself can be sent instead.
Closes #666

chore: update deps.dev repo finder to use latest API.

---

src/macaron/repo_finder/commit_finder.py
tests/e2e/repo_finder/commit_finder.py

This PR improves the Commit Finder so it can match in two additional tag usage cases:
- Where part of a suffix has a different case to the version it represents. E.g. rc4 vs RC4
- Where part of a suffix contains a number string with a different amount of preceding zeros to the version it represents.
Tests for these cases have been added to the regression data set.
Closes #684

chore: improve commit finder accuracy

---

tests/dependency_analyzer/cyclonedx/__snapshots__/test_cyclonedx.ambr
tests/dependency_analyzer/cyclonedx/defaults.ini
tests/dependency_analyzer/cyclonedx/test_cyclonedx.py

Updates the configuration file for the cyclonedx unit test that was previously performing remote calls due to containing URLs that required following redirection to resolve. The related test resource file is reverted to how it looked before the redirection resolution feature was added.
Closes #686

chore: disable redirect resolution in tests

---

scripts/dev_scripts/integration_tests.sh
src/macaron/slsa_analyzer/checks/build_script_check.py
tests/e2e/expected_results/purl/maven/com_example_nonexistent/nonexistent.json

Change build script check to fail on skip instead of pass, which became incorrect when the check dependency relationship was changed so that the build script check is skipped when the version control system check fails (and thus should likewise fail as no source or build script is available), rather than being skipped when the stronger build checks pass (which previously meant that build script would then pass by default).
Added an integration check to confirm that all checks fail for a purl referring to a nonexistent artifact.

fix: make build script check fail when no repo is found

---

scripts/release_scripts/run_macaron.sh

macOS does not support the `--parents` option in `mkdir`. This PR fixes the `run_macaron.sh` script by using the `-p` option instead to be compatible with macOS.

fix: fix a compatibility issue in run_macaron.sh for macOS

---

docs/source/pages/tutorials/generate_verification_summary_attestation.rst
docs/source/pages/tutorials/index.rst
docs/source/pages/using.rst
docs/source/pages/vsa.rst

This pull request adds a tutorial for the VSA generation feature, accounting for changes made in #685.
Some other minor modifications are made to also account for #685.

chore: add tutorial for VSA generation feature

---

docs/source/pages/output_files.rst
docs/source/pages/supported_technologies/index.rst
docs/source/pages/using.rst
scripts/dev_scripts/integration_tests.sh
src/macaron/config/defaults.ini
src/macaron/slsa_analyzer/git_service/__init__.py
src/macaron/slsa_analyzer/git_service/local_repo_git_service.py
tests/e2e/defaults/bitbucket_local_repo.ini
tests/e2e/expected_results/snakeyaml/snakeyaml.json

feat: allow defining a git service from defaults.ini  

---

src/macaron/errors.py
src/macaron/json_tools.py
src/macaron/parsers/actionparser.py
src/macaron/repo_finder/provenance_extractor.py
src/macaron/repo_finder/repo_finder_deps_dev.py
src/macaron/slsa_analyzer/analyzer.py
tests/repo_finder/test_provenance_extractor.py

This PR allows the provenance extractor to return partial results when either the repo URL or commit cannot be found. Tests have been updated to ensure this change works as intended while retaining the previous non-overlapping functionality, i.e. returning both, or neither on critical errors.
This change does not apply to SLSA v1 as these use the repo URL as a key to access the correct commit. To support this in SLSA v1 would require the repo URL be provided through some other means before provenance extraction begins.
Updates #707

chore: allow independent extraction of repo and commit from provenance

---

src/macaron/slsa_analyzer/analyzer.py

This Pull Request fixes the issue mentioned here - https://github.com/oracle/macaron/pull/698#issuecomment-2065609375
This can be seen as a continuation of https://github.com/oracle/macaron/pull/708
When the user provide only a repository path from `--repo-path` to Macaron without providing `--digest`. The expected behavior is that Macaron will use the repository path from the user provided `--repo-path` and try to extract the digest extracted from provenance if it's available (provided from user via `--provenance-file` or obtained from the PURL using provenance finder). 
This combination will be handled inside this block https://github.com/oracle/macaron/blob/e214326697aee6e31f0c9e406b11344c8619581e/src/macaron/slsa_analyzer/analyzer.py#L702-L708
However, its logic doesn't extract the …

fix: extract digest from provenance when repo path is provided but digest is not provided from the user

---

src/macaron/slsa_analyzer/checks/build_as_code_check.py

This PR fixes a bug in the build as code check. The `language` field in `BuildAsCodeFacts` was not set for non-GitHub CI services, which is needed for storing the result in the database.

fix: store language in build as code check for non-GitHub CI services

---

src/macaron/repo_finder/commit_finder.py

This PR includes a fix for the commit finder so that is supports the case where a version has only one part, but also consists of alphanumeric characters. Previously this would cause the only version part to become optional, and therefore allow invalid matches such as matching the entire tag as a prefix.
E.g. 
Version: `2012c`, Tag: `release_2012c`
`2012c` becomes optional allowing `release_2012c` to match as the prefix thereby preventing a proper match because the tag version part is empty.

chore: support versions with one alphanumeric part and a prefix in the commit finder

---

src/macaron/slsa_analyzer/checks/build_as_code_check.py
src/macaron/slsa_analyzer/checks/build_service_check.py
src/macaron/slsa_analyzer/ci_service/base_ci_service.py
tests/slsa_analyzer/ci_service/test_base_ci_service.py

This PR improves the log messages for build checks.

chore: improve log message for build checks

---

scripts/release_scripts/run_macaron.sh

fix: improve run_macaron.sh bash and docker version compatibility

---

docs/source/pages/installation.rst

Added a note in the Installation documentation page for the supported architecture. We will update it once https://github.com/oracle/macaron/issues/648 is addressed.

chore: add note for supporting only amd64 architecture at the moment

---

src/macaron/output_reporter/templates/macaron.html

Update the provenance status justification in the HTML report from `repository` to `the target software component`.

chore: update provenance status justification note in html report

---

docs/source/pages/using.rst
src/macaron/slsa_analyzer/git_url.py

For analyzing local repositories in offline mode, we should not fetch from `origin/HEAD` because user might want to run Macaron on the local changes. This PR changes the `check_out_repo_target` function to fix this issue: if `branch_name` and a commit are not provided, this function will not do anything and the latest local commit will be analyzed. If there are uncommitted local changes, the latest commit will appear in the report but the repo with local changes will be analyzed. We leave it up to the user to decide whether to commit the changes or not.

fix: do not fetch from origin/HEAD for local repo targets

---

scripts/dev_scripts/integration_tests.sh
src/macaron/repo_finder/commit_finder.py
src/macaron/slsa_analyzer/analyzer.py

This PR improves the commit finder so that it can handle cases where numeric version parts have preceding zeroes. E.g. Version `2024.2.2` -> Tag `2024.02.02`. The trailing zero evaluation (for the version as a whole) has also been updated to accept "long" zeros, e.g. `1.00`, `1.000`.
In addition, PURLs with an invalid type as defined in the spec are rejected before analysis begins.
Partially relates to discussion in #706

chore: improve commit finder and input handling

---

CONTRIBUTING.md

#749 updated `slsa-verifier` to version `v2.5.1` [which requires Go v1.21](https://github.com/slsa-framework/slsa-verifier/blob/eb7007070baa04976cb9e25a0d8034f8db030a86/go.mod#L5). Using an older Go version (v1.20 or below) causes `make setup` to fail due to a `go.mod` schema change ([specifically, the addition of the `toolchain` directive](https://go.dev/doc/modules/gomod-ref#toolchain)).
This pull request updates the required Go version in `CONTRIBUTING.md`.

docs: update required go version to 1.21

---

scripts/dev_scripts/integration_tests.sh
src/macaron/config/defaults.ini
src/macaron/json_tools.py
src/macaron/repo_finder/commit_finder.py
src/macaron/repo_finder/provenance_extractor.py
src/macaron/repo_finder/repo_finder_deps_dev.py
src/macaron/slsa_analyzer/analyzer.py
src/macaron/slsa_analyzer/package_registry/jfrog_maven_registry.py
src/macaron/slsa_analyzer/provenance/expectations/cue/cue_validator.py
src/macaron/slsa_analyzer/provenance/intoto/__init__.py
src/macaron/slsa_analyzer/provenance/intoto/v01/__init__.py
src/macaron/slsa_analyzer/provenance/intoto/v1/__init__.py
src/macaron/slsa_analyzer/provenance/loader.py
src/macaron/util.py
src/macaron/vsa/vsa.py
tests/e2e/expected_results/slsa-verifier/slsa-verifier_explicitly_provided_cue_PASS.json
tests/repo_finder/test_provenance_extractor.py
tests/slsa_analyzer/provenance/intoto/v01/test_validate.py
tests/slsa_analyzer/provenance/intoto/v1/test_validate.py
tests/slsa_analyzer/test_analyze_context.py
tests/slsa_analyzer/test_analyzer.py
tests/vsa/test_compare_vsa.py

Adds a validation step to analysis that ensures the passed repo and commit match those found in the passed provenance, if all of those exist.

chore: validate input repo, commit, provenance to ensure they match

---

src/macaron/repo_finder/repo_finder.py

This PR was to perform refactoring so that a possibly duplicated function could be removed, while implementing the original's TODO comment. Further investigation has revealed that the possibly duplicated function should remain, and that the TODO comment is outdated. Therefore this PR only removes the TODO comment.
Closes #752

chore: remove outdated TODO in repo finder function

---

scripts/release_scripts/run_macaron.sh

Using `--platform linux/amd64` makes it possible to run amd64 images on arm64 platforms through emulation
Closes #767

fix: force docker to use linux/amd64 platform

---

scripts/dev_scripts/integration_tests.sh
scripts/dev_scripts/integration_tests_docker.sh
src/macaron/__main__.py
src/macaron/policy_engine/prelude/helper_rules.dl
src/macaron/policy_engine/prelude/policy.dl
tests/e2e/expected_results/purl/maven/com_example_nonexistent/nonexistent.dl

This pull request includes the following fixes:
* A fix to the `verify-policy` command to exit with non-zero code when no "passed policy" exists.
* A fix to the policy rules allows components with no repository to pass policies.
* Fixes to some integration tests that did not fail when the component being verified did not pass the policy applied to it.

fix: modify verify-policy to exits succesfully if a passed policy exists and allow components having no repository to pass policies

---

src/macaron/repo_finder/provenance_extractor.py
tests/repo_finder/test_provenance_extractor.py

Adds support and unit tests for the new build type.

feat: add support for SLSA v1 provenance with OCI build type

---

.pre-commit-config.yaml
docs/README.md
scripts/dev_scripts/integration_tests.sh
scripts/dev_scripts/integration_tests_docker.sh
tests/integration/README.md
tests/integration/run.py

We have made `Python 3.11` a requirement for our development environment and use `python` to run. This PR replaces `python3` with `python` in develoment scripts to be consistent.

test: use python instead of python3

---

.gitignore
scripts/dev_scripts/integration_tests.sh
scripts/dev_scripts/integration_tests_docker.sh
scripts/release_scripts/run_macaron.sh
tests/integration/cases/apache_maven_local_repo/test.yaml
tests/integration/cases/apache_maven_purl_repo_path/test.yaml
tests/integration/cases/apache_maven_sbom/test.yaml
tests/integration/cases/apache_maven_yaml_input_skip_deps/test.yaml
tests/integration/cases/apache_maven_yaml_input_with_dep_resolution/test.yaml
tests/integration/cases/behnazh-w_example-maven-app/test.yaml
tests/integration/cases/invalid_purl/test.yaml
tests/integration/cases/no_branch_or_commit/test.yaml
tests/integration/cases/no_github_token/test.yaml
tests/integration/cases/ossf_scorecard/test.yaml
tests/integration/cases/run_macaron_sh_early_exit/test.yaml
tests/integration/cases/run_macaron_sh_with_invalid_docker_pull_env/test.yaml
tests/integration/cases/slsa-framework_slsa-verifier/test.yaml
tests/integration/cases/timyarkov_multibuild_test_gradle/test.yaml
tests/integration/cases/timyarkov_multibuild_test_maven/test.yaml
tests/integration/cases/urllib3_expectation_dir/test.yaml
tests/integration/cases/urllib3_expectation_file/test.yaml
tests/integration/cases/urllib3_invalid_expectation/test.yaml

This Pull Request improves token file operations in `run_macaron.sh`.
- Moved the token file creation to the end of `run_macaron.sh` so that if the script exits early, the token file is not persisted within the file system - https://github.com/oracle/macaron/pull/780/commits/f88f00ab4bf3544e202a8e0e6b7a624473883fbc
- Made sure that `docker run` if returns a non-zero status code doesn't trigger early exit (enable by `set -e`). This enables us to perform the cleaning up before exiting `run_macaron.sh`. Furthermore, the return status code of `run_macaron.sh` follows that of `docker run` - https://github.com/oracle/macaron/pull/780/commits/af4173ecd83a764aed279c41c7a12b84e79aa111
- Added integration test cases to check for token file persistence - …

chore: improve token support in run_macaron.sh

---

tests/integration/run.py

Setup the dev environment and run the following command:
```
python ./tests/integration/run.py update ./tests/integration/cases/...
...
AttributeError: 'Namespace' object has no attribute 'include_tag'
```
This is because here
https://github.com/oracle/macaron/blob/a06ed41d306d21da54a7e3135049c630b686c720/tests/integration/run.py#L955-L964
we create option parsers  for `--excluded-tag` and `--include-tag` which are necessary for the update command of Macaron later 
https://github.com/oracle/macaron/blob/a06ed41d306d21da54a7e3135049c630b686c720/tests/integration/run.py#L1010-L1016

chore: add exclude and include tag options to update command and add logging of each test case to update command

---

tests/policy_engine/resources/policies/django/test_dependencies.dl

Uses the policy string match rule to allow for any non-major version change in the two dependencies.

chore: update django dependency policy to ignore minor version changes

---

pyproject.toml

I don't understand why suddenly this issue was picked up by `mypy` because we were using version [`1.10.1`](https://github.com/python/mypy/releases/tag/v1.10.1). Anyway, I have also updated `mypy`'s version range to use [version `1.11.0`](https://github.com/python/mypy/releases/tag/v1.11.0).
Fixes #798

chore(mypy): remove redundant mypy_path configuration for type checking

---

docs/source/pages/installation.rst

I tried running Macaron on my Mac and it failed because Docker wasn’t able to write to the host fs. This change adjusts the instructions with the fix.

docs: update Installation Guide with Docker Desktop instructions

---

src/macaron/malware_analyzer/pypi_heuristics/sourcecode/suspicious_setup.py

Right now the `CLOSER_RELEASE_JOIN_DATE` heuristic in the `mcn_detect_malicious_metadata_1` check does not depend on any other heuristic results. However, all the heuristic combinations require the `CLOSER_RELEASE_JOIN_DATE` heuristic to fail. This PR adds the `CLOSER_RELEASE_JOIN_DATE` heuristic as a dependency of `SUSPICIOUS_SETUP` to avoid running `SUSPICIOUS_SETUP` analyzer unnecessarily and improve performance.

chore: add CLOSER_RELEASE_JOIN_DATE heuristic as a dependency of SUSPICIOUS_SETUP

---

Makefile
pyproject.toml

`cfgv` and `ruamel.yaml`, which are needed for Docker integration tests were missing from the `pyproject.toml`. because the GitHub Action job that runs the docker tests only needs these deps and not the rest, to improve CI runtime I have added a new `test-docker` set of optional dependencies which will by default be installed by the `setup` target in the `Makefile`.

chore(deps-dev): add test-docker dependencies to pyproject.toml

---

docs/source/conf.py
docs/source/pages/developers_guide/apidoc/macaron.parsers.rst
docs/source/pages/developers_guide/apidoc/macaron.slsa_analyzer.checks.rst

This excludes hyphenated attributes for the `make docs` command preventing Sphinx errors relating to them.
E.g.
> invalid signature for autoattribute ('macaron.parsers.github_workflow_model::Step5.working-directory')
These attributes are valid, only not accepted by Sphinx.

docs: exclude hyphenated attributes in sphinx docs

---

THIRD_PARTY_LICENSES.txt

This PR updates `Third_party_licenses.txt` for v0.12.0 with 3p attribution notices for Beautiful soup 4.12.3.

chore: update third party license file for v0120

---

docs/source/pages/tutorials/npm_provenance.rst

chore: correct typo in npm provenance tutorial

---

tests/integration/cases/google_guava/policy.dl

The [GitHub API](https://api.github.com/repos/google/guava/actions/runs/5719444145/jobs) does not return the information related to the `steps` of the workflow run for `guava@32.1.2-jre`any longer. This PR disables the related integration test. I will adjust the logic of this check in the refactored version.
Closes https://github.com/oracle/macaron/issues/854

test: disable mcn_infer_artifact_pipeline_1 for guava

---

docs/source/pages/developers_guide/index.rst

docs: mention that check files should end with _check suffix

---

Makefile
scripts/dev_scripts/copyright-checker.sh

- Install gnu-sed as part of `setup` (`setup-binaries`). 
- Use `gsed` in `copyright-checker.sh` when running on mac.
Closes #852

fix: use gnu-sed on mac instead of the built-in sed command

---

src/macaron/config/defaults.ini
src/macaron/util.py
tests/test_util.py

This PR prevents GET requests made by Macaron from looping endlessly when receiving a 403 error that is not related to GitHub's API rate limit. It also adds a configurable retry limit that applies to all request failures.
Closes #865

fix: prevent endless loop on 403 GitHub response

---

Makefile

This PR makes the following improvements to the `souffle` goal of the `Makefile`:
- A new comment that explains the behavior when Souffle cannot be installed automatically.
- Ensured consistent indentation and spacing for readability based on recommendations in https://github.com/oracle/macaron/pull/877
- Prints a useful message when the OS distribution is not supported.
cc @jenstroeger

chore: improve the indentation consistency of souffle Makefile goal

---

Makefile

Fix to PR https://github.com/oracle/macaron/pull/853 (tagging @mabdollahpour-ol)
The Makefile goal assumed [Brew](https://brew.sh/) only, so I added support for [Ports](https://www.macports.org/) and a check for `gsed` to avoid installing it twice. Also note that at least Ports aliases `gsed` as `sed` such that 
https://github.com/oracle/macaron/blob/edfe06eb3f9337f86215b253f40f53ca1a0105c9/scripts/dev_scripts/copyright-checker.sh#L55-L59
becomes irrelevant. I don’t know how Brew manages overriding macOS CLI tools with GNU tools.
Furthermore, I cleaned up indentation to be consistent with most (not all!) of the Makefile: every line of a rule indents by a single tab, then two spaces within scripts. That way it is easier to tell the difference between tab-indent (four or eight, depending on …

chore: fix Makefile goal `gnu-sed` to handle brew, port, and GNU sed on macOS gracefully

---

pyproject.toml

This change is part of issue https://github.com/oracle/macaron/issues/876 and prepares the `pyproject.toml` file for the optional plugins. I also sorted the existing disabled checkers alphabetically, and enabled the [suggestion mode](https://pylint.pycqa.org/en/latest/user_guide/configuration/all-options.html#suggestion-mode).[^1]
If we can merge this first then other lint fixes can just add their respective plugins with a one-line change.
[^1]: Huh, as of `pylint` v4 it defaults to `True` anyway, so perhaps that setting will become redundant anyway.

chore: add suggestion mode to pylint settings, and silence the “too many try statements” checker

---

pyproject.toml
src/macaron/slsa_analyzer/build_tool/docker.py
src/macaron/slsa_analyzer/build_tool/go.py
src/macaron/slsa_analyzer/build_tool/gradle.py
src/macaron/slsa_analyzer/build_tool/maven.py
src/macaron/slsa_analyzer/build_tool/npm.py
src/macaron/slsa_analyzer/build_tool/pip.py
src/macaron/slsa_analyzer/build_tool/yarn.py
src/macaron/slsa_analyzer/package_registry/jfrog_maven_registry.py
src/macaron/slsa_analyzer/package_registry/maven_central_registry.py
src/macaron/slsa_analyzer/package_registry/npm_registry.py
src/macaron/slsa_analyzer/package_registry/pypi_registry.py
src/macaron/slsa_analyzer/provenance/intoto/v01/__init__.py
src/macaron/slsa_analyzer/provenance/intoto/v1/__init__.py
src/macaron/slsa_analyzer/registry.py

This change is part of issue #876 and addresses the [`consider-using-any-or-all`](https://pylint.pycqa.org/en/latest/user_guide/messages/convention/consider-using-any-or-all.html) check messages.

chore: fix pylint message consider-using-any-or-all

---

pyproject.toml
src/macaron/repo_finder/provenance_finder.py
src/macaron/repo_finder/repo_finder.py
src/macaron/slsa_analyzer/ci_service/github_actions/analyzer.py
src/macaron/slsa_analyzer/git_url.py
src/macaron/slsa_analyzer/provenance/expectations/expectation_registry.py

This change is part of issue #876 and addresses the [`use-set-for-membership`](https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/use-set-for-membership.html) check messages.

chore: fix pylint message use-set-for-membership

---

pyproject.toml
src/macaron/config/defaults.py
src/macaron/dependency_analyzer/cyclonedx.py

This change is part of issue #876 and addresses the [`overlapping-except`](https://pylint.pycqa.org/en/latest/user_guide/messages/warning/overlapping-except.html) check messages. Because all errors were already handled in a single `except` I left it that way — if errors need to be handled according to their error class hierarchy (e.g. `shutil.Error` is a subclass of `OSError`) then please let me know.

chore: fix pylint message overlapping-except

---

pyproject.toml
src/macaron/database/database_manager.py

This change is part of issue #876 and addresses the [`deprecated-typing-alias`](https://pylint.pycqa.org/en/latest/user_guide/messages/warning/deprecated-typing-alias.html) check messages.

chore: fix pylint message deprecated-typing-alias

---

pyproject.toml
src/macaron/repo_finder/commit_finder.py
src/macaron/slsa_analyzer/ci_service/github_actions/analyzer.py
tests/integration/run.py

This change is part of issue #876 and addresses the [`else-if-used`](https://pylint.pycqa.org/en/latest/user_guide/messages/refactor/else-if-used.html) check messages.

chore: fix pylint message else-if-used

---

docs/source/pages/cli_usage/command_find-source.rst
docs/source/pages/developers_guide/apidoc/macaron.repo_finder.rst
docs/source/pages/developers_guide/apidoc/macaron.slsa_analyzer.checks.rst
docs/source/pages/tutorials/index.rst
docs/source/pages/tutorials/source_finder.rst
tests/integration/cases/tutorial_source_finder/check_output.sh
tests/integration/cases/tutorial_source_finder/test.yaml

Adds a tutorial for the new find source command, and updates the docs for the command itself.

docs: add tutorial for find source command

---

src/macaron/repo_finder/repo_finder.py
src/macaron/slsa_analyzer/git_url.py
tests/integration/cases/find_source_fail/test.yaml

Applies a fix for the standalone commit finder feature: preventing login related terminal prompts from interrupting the process.

fix: block terminal prompts in find source

---

src/macaron/slsa_analyzer/checks/infer_artifact_pipeline_check.py
src/macaron/slsa_analyzer/ci_service/github_actions/github_actions_ci.py
tests/integration/cases/micronaut-projects_micronaut-test/micronaut-test.dl

The GitHub API for some reason does not anymore return the steps information of the job that has published `pkg:maven/io.micronaut.test/micronaut-test-junit5@4.5.0` even though it was published in Aug 2024, which is much earlier than [the 400 retention policy](https://docs.github.com/en/rest/guides/using-the-rest-api-to-interact-with-checks?apiVersion=2022-11-28#retention-of-checks-data). This PR raises a new exception to handle this case and allows the corresponding integration test to fail.

test(integration): handle missing steps info in GitHub API response

---

docs/source/index.rst
docs/source/pages/tutorials/detect_malicious_package.rst
src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py
src/macaron/util.py
tests/integration/cases/tautoak4-hello-world/policy.dl
tests/integration/cases/tautoak4-hello-world/test.yaml
tests/integration/cases/type-extension/policy.dl
tests/integration/cases/type-extension/test.yaml

If a package is already known to be malicious, this PR reports it as part of the `mcn_detect_malicious_metadata_1` check. Additionally, two new integration tests for known Python and npm malware have been added.

feat: report known malware for all ecosystems

---

docs/source/_static/schemastore/find_source_report_schema.json
docs/source/pages/tutorials/source_finder.rst
src/macaron/resources/schemastore/find_source_report_schema.json
tests/integration/run.py
tests/repo_finder/test_report_schema.py

This PR fixes issues in the source finder tutorial.
It also moves the source finder report JSON schema to `src/macaron/resources/schemastore/`, and references it from the tutorial.

docs: fix issues and improve the source finder tutorial

---

src/macaron/database/table_definitions.py
src/macaron/errors.py
src/macaron/malware_analyzer/pypi_heuristics/heuristics.py
src/macaron/malware_analyzer/pypi_heuristics/metadata/wheel_absence.py
src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py
tests/integration/cases/ajax-requester_pypi_malware_analyzer/policy.dl
tests/integration/cases/ajax-requester_pypi_malware_analyzer/test.yaml
tests/malware_analyzer/pypi/test_wheel_absence.py

A new heuristic has been added to the PyPI package malware analyzer heuristics that checks if the specified package and version is available as a wheel (.whl) file. The rationale behind this is that, if a malicious package has a suspicious setup file (setup.py), then it will omit a wheel file in the package so that when installed, the setup file will be run automatically. This new heuristic passes if there is a wheel file available, and fails if there is not. It has been added to the suspicious combinations (SUSPICIOUS_COMBO) such that, when the suspicious setup heuristic fails, this heuristic must fail. When the suspicious setup heuristic passes, this heuristic is indifferent and has no effect.
New files added to the project are:
- …

feat: add a new setup.py related heuristic in the pypi malware analyzer

---

src/macaron/malware_analyzer/pypi_heuristics/metadata/wheel_absence.py
src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py
src/macaron/util.py
tests/malware_analyzer/pypi/test_wheel_absence.py

To allow for retention of packages when they are taken off PyPI, this new feature includes the inspector.pypi.io URL for the distribution files as part of the `MaliciousMetadataFacts` `detail_information` field. This has been done by modifying the `wheel_absence.py` heuristic to instead of returning filenames, return the python hosted URL and corresponding pypi inspector URL. The unit test for this, `test_wheel_absence.py` has been updated to reflect these changes accordingly.

feat: include inspector package urls as part of the malicious metadata facts for pypi packages

---

tests/repo_finder/test_commit_finder.py

This PR prevents the commit finder tests from hanging when the user has configured their Git environment to require gpg signing for tags, as noted by #938. This is achieved by overriding the configuration value for the temporary repository created by the test.
Closes #938

chore: disable gpg signing for commit finder tests

---

docs/source/pages/developers_guide/apidoc/macaron.malware_analyzer.pypi_heuristics.metadata.rst

Addressing issue #942, the `make docs-api` command has been run and has included an entry in `macaron.malware_analyzer.pypi_heuristics.metadata.rst` with the following content:
```
macaron.malware\_analyzer.pypi\_heuristics.metadata.wheel\_absence module
-------------------------------------------------------------------------
.. automodule:: macaron.malware_analyzer.pypi_heuristics.metadata.wheel_absence
:members:
:undoc-members:
:show-inheritance:
```

docs: add in the api docs entry for wheel absence heuristic

---

docs/source/pages/cli_usage/command_analyze.rst
scripts/release_scripts/run_macaron.sh
src/macaron/__main__.py
src/macaron/artifact/local_artifact.py
src/macaron/artifact/maven.py
src/macaron/config/global_config.py
src/macaron/errors.py
src/macaron/slsa_analyzer/analyze_context.py
src/macaron/slsa_analyzer/analyzer.py
src/macaron/slsa_analyzer/package_registry/jfrog_maven_registry.py
tests/artifact/test_local_artifact.py
tests/artifact/test_maven.py
tests/integration/cases/docker_local_maven_repo_input_errors/test.yaml
tests/integration/cases/run_macaron_sh_script_unit_test/test_run_macaron_sh.py
tests/slsa_analyzer/package_registry/test_jfrog_maven_registry.py

Closes #811 
This pull request adds the following features:
- The ability to provide Macaron with a [maven local repository](https://maven.apache.org/repositories/local.html)
- The ability to resolve the directories that contains artifacts corresponding to a PackageURL from the Maven local repository and/or the Python virtual environment.
A new CLI parameter is added `--local-maven-repo` that takes a path to a maven local repo. This flag is optional.
If `--local-maven-repo` is not used, Macaron will load the path to the local maven repo (at `$HOME/.m2`) if that directory is available.
Macaron will treat this maven local repo as *READ-ONLY*.
If `--local-maven-repo` is provided to `run_macaron.sh`, the directory provided with this flag is mount to …

feat: obtain Java and Python artifacts from .m2 or Python virtual environment from input

---

src/macaron/repo_finder/repo_finder.py
src/macaron/repo_finder/repo_finder_deps_dev.py
src/macaron/repo_finder/repo_finder_java.py
src/macaron/repo_finder/repo_utils.py
src/macaron/slsa_analyzer/analyzer.py
tests/integration/cases/latest_repo_comparison/check_output.sh
tests/integration/cases/latest_repo_comparison/test.yaml
tests/integration/cases/repo_finder_remote_calls/repo_finder.py

This PR improves the Repo Finder by making it check for repositories using the latest version of an artifact if the provided version does not contain that information. This latest version finding behaviour is also added for the case where a Java PURL was provided without a version, and is added for the `find-source` command.

feat: find repo from latest artifact when provided artifact has none

---

src/macaron/config/defaults.ini
src/macaron/malware_analyzer/pypi_heuristics/metadata/wheel_absence.py
src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py
src/macaron/slsa_analyzer/package_registry/pypi_registry.py
tests/malware_analyzer/pypi/test_wheel_absence.py
tests/slsa_analyzer/checks/test_detect_malicious_metadata_check.py

The `detect_malicious_metadata` check is expected to `FAIL` for `pkg:pypi/zlibxjson` by running the heuristics, but a false negative has been introduced after the addition of the wheel presence heuristic. The unit test was passing because if the unit test was able to access the OSV knowledge base, it would identify the package as a known malware without running the heuristics. However, to ensure unit tests remain offline, network access is intentionally blocked and because of that the check passes. There is a TODO to fix this regression after adding better code-based heuristics.
This PR modifies the API URL configurations to make them compatible with offline unit tests, ensuring they work without requiring network access.

test: block the malware detection unit test from reaching network

---

docs/source/pages/developers_guide/apidoc/macaron.slsa_analyzer.package_registry.rst
src/macaron/config/defaults.ini
src/macaron/errors.py
src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py
src/macaron/slsa_analyzer/package_registry/deps_dev.py
src/macaron/slsa_analyzer/package_registry/jfrog_maven_registry.py
src/macaron/slsa_analyzer/package_registry/maven_central_registry.py
src/macaron/slsa_analyzer/package_registry/package_registry.py
tests/integration/cases/ultralytics/policy.dl
tests/integration/cases/ultralytics/test.yaml
tests/integration/cases/ultralytics_8.3.46/policy.dl
tests/integration/cases/ultralytics_8.3.46/test.yaml
tests/slsa_analyzer/checks/test_detect_malicious_metadata_check.py
tests/slsa_analyzer/package_registry/test_deps_dev.py
tests/slsa_analyzer/package_registry/test_npm_registry.py

Some of the malicious packages are not clearly labeled in the OSV knowledge base. This PR improves the known malware detection in `detect_malicious_metadata_check`. It also adds a new abstraction for the deps.dev service to improve code reusability.

fix: report known malware even when not labeled

---

src/macaron/slsa_analyzer/git_url.py
tests/integration/cases/update_local_repositories/modify_clone.sh
tests/integration/cases/update_local_repositories/policy.dl
tests/integration/cases/update_local_repositories/test.yaml

This fixes the issue with previously cloned repositories not updating when newer changes are present at their remote origins, by using `git fetch` when the target directory of the clone is already present. This comes with a small performance hit for any analysis performed on a previously cloned target.
Closes #948

fix: update already present repositories

---

docs/source/pages/developers_guide/apidoc/macaron.malware_analyzer.pypi_heuristics.metadata.rst

The entry for the anomalous version heuristic was missing in `macaron.malware_analyzer.pypi_heuristics.metadata.rst`, so `make docs-api` has been run to include it.

docs: add in the api docs entry for anomalous version heuristic

---

src/macaron/database/views.py

This PR refactors the view creation process to avoid using internal SQLAlchemy functions, ensuring the implementation relies solely on the officially supported functions and best practices. 
Additionally, it enhances the docstrings for the related functions to provide clearer and more detailed explanations.

chore(deps): fix the compatibility issue introduced by SQLAlchemy 2.0.38

---

src/macaron/malware_analyzer/README.md
src/macaron/malware_analyzer/pypi_heuristics/metadata/anomalous_version.py
src/macaron/malware_analyzer/pypi_heuristics/metadata/closer_release_join_date.py
src/macaron/malware_analyzer/pypi_heuristics/metadata/empty_project_link.py
src/macaron/malware_analyzer/pypi_heuristics/metadata/high_release_frequency.py
src/macaron/malware_analyzer/pypi_heuristics/metadata/one_release.py
src/macaron/malware_analyzer/pypi_heuristics/sourcecode/suspicious_setup.py

This PR includes the `anomalous_version` and `wheel_absence` heuristics in `src/macaron/malware_analyzer/README.md`, as a description of them was missing. In doing so, this PR refactors that file to reflect the current state of the malware analyzer, along with some of the docstrings for those heuristics. This is a separate PR so upcoming ones like #965 and #983 can make changes to it.

docs: include new heuristics in malware analyzer readme

---

docs/source/pages/cli_usage/command_analyze.rst
src/macaron/__main__.py

refactor: remove the deprecated --skip-deps command-line option.

---

tests/artifact/test_local_artifact.py

Handling filesystem specific case sensitivity, by creating temporary files and checking if they point towards same file using their inodes. This fixes #992

test: fix unit test case sensitivity

---

docs/source/pages/installation.rst

Added a hyperlink for the UTM virtualization tool as a workaround for running the run_macaron.sh script on aarch64 architecture.
This commit fixes #976

docs: add hyperlink for UTM virtualization tool in documentation

---

src/macaron/config/defaults.ini
src/macaron/repo_finder/repo_finder.py
tests/integration/cases/apache_maven_sbom/config.ini
tests/integration/cases/apache_maven_sbom/test.yaml

This PR adds a configuration option to disable the latest PURL retrieval feature, and disables the feature in the `apache_maven_sbom` integration test so that the results of that test are static.
Closes #1010

chore: add config option to disable latest PURL retrieval

---

pyproject.toml
src/macaron/malware_analyzer/README.md
src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py

Refactor the `SUSPICIOUS_COMBOS` dictionary to instead use a `problog` model. The purpose of this is to simplify the dictionary into logical statements, and allow for future development of probabilistic rules. This model transforms the `HeuristicResult` types as follows:
- `HeuristicResult.FAIL` results in `<name> :- false.`
- `HeuristicResult.PASS` results in `<name> :- true.`
- `HeuristicResult.SKIP` results in `0.0::<name>`, which means any rules which require this heuristic do not trigger.
To do:
Current issues with including `problog` that need to be resolved:
- This will be kept the same. Type hints are offered manually in the code where it was used in `detect_malicious_metadata_check.py`
```
=============================== warnings summary =============================== …
```

refactor: use problog for suspicious combinations

---

docs/source/pages/developers_guide/index.rst

This adds information on how to regenerate the database diagram in the developer's guide.

docs: add database diagram instructions

---

src/macaron/config/defaults.ini
src/macaron/slsa_analyzer/analyzer.py
src/macaron/slsa_analyzer/build_tool/base_build_tool.py
src/macaron/slsa_analyzer/checks/build_as_code_check.py
src/macaron/slsa_analyzer/checks/build_service_check.py
src/macaron/slsa_analyzer/checks/infer_artifact_pipeline_check.py
src/macaron/slsa_analyzer/ci_service/jenkins.py
tests/integration/cases/org_apache_dubbo_dubbo-rpc-memcached/policy.dl
tests/integration/cases/org_apache_dubbo_dubbo-rpc-memcached/test.yaml

This PR introduces the construction of callgraphs for bash scripts inlined within `Jenkinsfile` configurations. Additionally, it creates `BuildToolCommand` objects, which will be utilized in the build-related checks. With this update, Jenkins is no longer categorized as an unparsed CI service, although parsing support remains partial.
- An integration test has been added for the `pkg:maven/org.apache.dubbo/dubbo-rpc-memcached@2.7.7` artifact, which uses Jenkins for builds.
- The expected result in `tests/integration/cases/jenkinsci_plotplugin` has been updated to reflect the absence of a build service command.
Similar to GitHub Actions, we aim to support recursive calls to bash scripts within `Jenkinsfile`. The implementation should be straightforward, but it is recommended to first …

feat: add callgraph and build cmd detection for Jenkins

---

src/macaron/repo_finder/repo_finder_deps_dev.py
tests/integration/cases/google_guava_latest/policy.dl
tests/integration/cases/google_guava_latest/test.yaml

When retrieving versions of artefacts from `deps.dev` API, one of the entries will have the `isDefault` property set to `True`. It is this version that is considered to be the latest version in the list, not the last entry as was previously assumed.
Closes #1018

fix: use 'isDefault' version from deps dev api

---

Makefile

Souffle has released a new version to address the issue with `libffi`. See #962 
The new release is not yet available using `apt get` in Ubuntu. While it is unavailable, the released Ubuntu package will be manually installed instead.
Reverts oracle/macaron#964

build: install souffle 2.5 for ubuntu manually

---

src/macaron/database/views.py

This PR addresses #1033 by adjusting the argument types to accommodate a recent [change](https://github.com/sqlalchemy/sqlalchemy/commit/e279b737c34bc0a1b335b272862dc42be79522c3#diff-0a2372170f9ad003cabd7347c94edb62d095be37dc20f2742650202b5341c774R97) in SQLAlchemy, which would otherwise cause structural type checking failures in mypy.

chore(deps): update the argument types of SQLAlchemy callables

---

docs/source/pages/tutorials/detect_malicious_java_dep.rst
tests/integration/cases/log4j_release_pipeline/policy.dl
tests/integration/cases/log4j_release_pipeline/test.yaml

This PR changes the version of `org.apache.logging.log4j:log4j-core` to a newer version, as the GitHUb pipeline for the older version is removed.

test(ci): update log4j-core@3.0.0-beta2 to log4j-core@3.0.0-beta3

---

src/macaron/__main__.py
src/macaron/config/global_config.py
src/macaron/dependency_analyzer/cyclonedx.py
src/macaron/output_reporter/reporter.py
src/macaron/parsers/bashparser.py
src/macaron/provenance/provenance_verifier.py
src/macaron/repo_finder/repo_utils.py
src/macaron/slsa_analyzer/ci_service/base_ci_service.py
src/macaron/slsa_analyzer/provenance/expectations/cue/__init__.py
src/macaron/slsa_analyzer/provenance/expectations/expectation_registry.py

refactor: log relative paths for file

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/config.yaml
.github/ISSUE_TEMPLATE/feature_request.md

This PR introduces two new issue templates to the repository:
- Bug Report Template: A structured template for users to report bugs effectively. It includes sections for detailed descriptions, steps to reproduce, expected vs. actual behavior, and environment information (such as operating system, Docker version, etc.). Additionally, it encourages users to provide debug information by running the command with the --verbose option to help diagnose issues more easily.
- Feature Request Template: A template to guide users when submitting feature requests. It helps ensure that requests are detailed enough to understand the intended feature, why it's useful, and any specific implementation details or suggestions.

chore: add bug and feature issue templates

---

.github/dependabot.yaml
.github/pull_request_template.md
.github/workflows/_generate-rebase.yaml
.github/workflows/codeql-analysis.yaml
.github/workflows/release.yaml
CONTRIBUTING.md
docs/source/pages/installation.rst
docs/source/pages/tutorials/detect_malicious_java_dep.rst
docs/source/pages/tutorials/use_verification_summary_attestation.rst

This pull request refactors the current branching model to improve development and address several challenges associated with using `staging` as the default base branch for pull requests. With this update, `main` will serve as the base branch for pull requests, containing active development changes, while releases will be triggered upon merging pull requests into the newly created `release` branch.
A new protected branch, named `release`, should be created if it doesn't already exist. This branch will be configured with security settings and essential checks to ensure the integrity and stability of the release process.
- Security scanning tool compatibility: most security tools scan the default branch, which is `main` in this project. However, if `staging` is used as the base branch for …

build: change the release and staging branching model

---

src/macaron/malware_analyzer/README.md
src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py
tests/slsa_analyzer/checks/test_detect_malicious_metadata_check.py

Addressing issue identified in #1027, where skips were being evaluated as false. This PR introduces wrappers `passed()` and `failed()` into the ProbLog model that use `try_call()` statements. Skipped heuristics are no longer defined in the ProbLog model, which is why this `try_call()` statement is used. This means that evaluating `failed(heuristic)` will be false if the heuristic passed, or if it was not defined (i.e. was skipped). Similarly, for evaluating `passed()`, this will be false if the heuristic failed, or if it was not defined. This should handle situations where skips should not cause rules they are part of to trigger. This method was the easiest way to keep as much of the ProbLog model in a static string as possible, without having to perform extensive string operations.
Rule …

fix: fix incorrect skip result evaluation causing false positives in PyPI malware reporting"

---

src/macaron/provenance/provenance_verifier.py

This PR fixes a bug where error output can be None during provenance verification. In these cases, a simple textual output is produced instead using the type of error encountered.
Closes #1045

chore: check for None type in error output

---

tests/integration/cases/apache_maven_local_path_with_branch_name_digest_deps_cyclonedx_maven/config.ini
tests/integration/cases/apache_maven_local_path_with_branch_name_digest_deps_cyclonedx_maven/test.yaml

This PR disables the latest PURL feature of the Repo Finder for the integration test `apache_maven_local_path_with_branch_name_digest_deps_cyclonedx_maven`. This prevents a mismatch in the source URL of dependency `ommons-jxpath:commons-jxpath` which recently updated its SCM metadata with a resolvable URL.
A config file is added to the test to disable the option.
Closes #1061

chore: disable latest purl finding for test

---

src/macaron/slsa_analyzer/analyzer.py

Refactor logging behavior to print the SLSA summary only when verbose mode is enabled. We can revisit if the summary should be removed or improved in the verbose mode in the future.
This PR updates the logging to ensure the SLSA summary is printed only when the application is run in verbose mode. Previously, the summary was always printed regardless of the verbosity level, which could result in unnecessary output in standard use cases.
This change helps reduce noise in the logs for users who do not require detailed internal information, while still allowing full visibility during debugging or detailed inspection when verbose mode is explicitly enabled.

refactor: log the SLSA summary in verbose mode only

---

src/macaron/errors.py
src/macaron/slsa_analyzer/git_url.py
src/macaron/slsa_analyzer/package_registry/osv_dev.py

This PR adds a utility function to identify the highest semantic version tag from a set of Git tags, specifically for cases where multiple tags point to the same commit SHA in a third-party GitHub Action. This is necessary because a single release may have multiple tag aliases, such as `v4` and `v4.2.1` and we want to consistently resolve to the most specific and recent tag.
The new `find_highest_git_tag` function uses Python’s `packaging.version` module to determine the highest (most recent) version according to semantic versioning rules. It handles common edge cases such as empty tag sets and invalid version strings, raising a custom `GitTagError` when appropriate.
This functionality is especially useful for automation workflows that need to programmatically resolve the latest stable …

chore: add support for Git tag aliases in vuln GHA check

---

.github/workflows/build_semgrep_wheel.yaml

This PR adds support for building [Semgrep ](https://github.com/semgrep/semgrep) from source and including it as a Macaron dependency.
This PR introduces a new manually-triggered GitHub action that clones the Semgrep GitHub repository for version 1.113.0 and builds the software as a python wheel package from source using the repository's supplied Docker file. This includes building from source the required OCaml binaries that are part of the package. This action publishes a minimal docker image under the name `macaron-deps` that only holds that build-from-source semgrep wheel with the name `semgrep_wheel.whl` in the top-level directory. The intention is for this artifact to be used in the final docker build in `Dockerfile.final` to copy the Semgrep wheel out into the Macaron image and …

build: add built-from-source github action for semgrep

---

pyproject.toml
src/macaron/config/defaults.ini
src/macaron/provenance/provenance_extractor.py
src/macaron/provenance/provenance_finder.py
src/macaron/provenance/provenance_verifier.py
src/macaron/repo_finder/repo_finder_deps_dev.py
src/macaron/repo_finder/repo_finder_enums.py
src/macaron/slsa_analyzer/analyzer.py
src/macaron/slsa_analyzer/package_registry/deps_dev.py
src/macaron/slsa_analyzer/package_registry/pypi_registry.py
src/macaron/slsa_analyzer/provenance/intoto/__init__.py
src/macaron/slsa_analyzer/provenance/loader.py
src/macaron/slsa_analyzer/specs/inferred_provenance.py
src/macaron/slsa_analyzer/specs/pypi_certificate_predicate.py
tests/conftest.py
tests/integration/cases/pypi_attestation_discovery/policy.dl
tests/integration/cases/pypi_attestation_discovery/test.yaml
tests/integration/cases/repo_finder_remote_calls/repo_finder.py
tests/provenance/test_provenance_finder.py
tests/repo_finder/test_repo_finder_deps_dev.py
tests/slsa_analyzer/package_registry/test_deps_dev.py

This PR adds discovery of PyPI attestation. URLs to these attestation files are sought via the deps.dev API.
- `DepsDevRepoFinder` was updated to use the `DepsDevService`, ensuring consistent and easily configurable use of the API
- Tests were added for `DepsDevRepoFinder` functions (they were not added previously), including for the functions that PyPI attestation discovery relies upon.
- PyPI attestations do not have a predicate. The `pypi-attestation` is used to extract information from the attestation certificate. This information is coerced into a predicate for use elsewhere within Macaron.
- Addition of an integration test case using the `ultralytics` Python library as its target.
Closes #947

feat: add pypi attestation discovery

---

.github/workflows/build_semgrep_wheel.yaml

This PR fixes the Docker image path used for building the Semgrep dependency. The previous image references were incorrect.

build: fix the Semgrep Docker image path

---

.github/workflows/_build_docker.yaml
.github/workflows/build_semgrep_wheel.yaml
docker/Dockerfile.final

Include the built-from-source Semgrep wheel stored in `macaron-deps` in the final docker image for macaron.
The minimal image `macaron-deps` that was created in #1073 (fixed in #1078) stores the python `.whl` package for Semgrep, built from source in a new GitHub action. After now confirming the image has been published successfully, this PR now uses this image to include the built-from-source Semgrep wheel in the final docker image for Macaron using multistage Docker builds.
There were some necessary changes to the Semgrep image made in this PR. The name of the `.whl` file must be maintained from the build inside the docker container for `pip` to use it properly, so this was updated and changed. 
Inside the final docker build, `Dockerfile.final`, this wheel is now copied into the image …

build: include semgrep in final docker image

---

src/macaron/repo_finder/repo_finder_deps_dev.py
src/macaron/repo_finder/repo_finder_pypi.py

This PR includes some small fixes found during a set of recent experiments.
Fixes:
- Assets stored within the PyPI registry metadata should only be compared via name, not version as well
- The deps.dev purl endpoint function does not need the class to be instantiated first
- The deps.dev repo finder should retrieve the latest version for purls with no version

chore: add small fixes

---

README.md
docs/source/index.rst

This PR improves the clarity and content of the README.md and the summary section of the documentation website for Macaron. 
- Refined and shortened the project summary in README.md for better readability
- Emphasized key features such as attestation support, reproducible builds, and malicious artifact detection
- Added references to tutorials and relevant blog posts

docs: improve the README.md and summary in the documentation website

---

src/macaron/artifact/local_artifact.py
src/macaron/artifact/maven.py
src/macaron/malware_analyzer/pypi_heuristics/sourcecode/suspicious_setup.py
src/macaron/repo_finder/repo_finder.py
src/macaron/repo_finder/repo_finder_pypi.py
src/macaron/slsa_analyzer/analyzer.py
src/macaron/slsa_analyzer/checks/build_script_check.py
src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py
src/macaron/slsa_analyzer/checks/provenance_commit_check.py
src/macaron/slsa_analyzer/checks/provenance_repo_check.py
src/macaron/slsa_analyzer/git_service/api_client.py
src/macaron/slsa_analyzer/package_registry/maven_central_registry.py
src/macaron/slsa_analyzer/package_registry/package_registry.py
src/macaron/slsa_analyzer/package_registry/pypi_registry.py
src/macaron/slsa_analyzer/provenance/loader.py
tests/artifact/test_local_artifact.py
tests/artifact/test_maven.py
tests/integration/cases/github_maven_attestation/policy.dl
tests/integration/cases/github_maven_attestation/test.yaml
tests/integration/cases/github_maven_attestation_local/policy.dl
tests/integration/cases/github_maven_attestation_local/test.yaml
tests/integration/cases/github_pypi_attestation/policy.dl
tests/integration/cases/github_pypi_attestation/test.yaml
tests/slsa_analyzer/package_registry/test_maven_central_registry.py

This PR adds support for GitHub attestation discovery. To access GitHub attestations, the SHA256 hash of the repositories artefacts must be generated and submitted via the API. Artefacts may be found in local caches, or downloaded from remote repositories.
Closes #915

feat: add GitHub attestation discovery

---

src/macaron/malware_analyzer/pypi_heuristics/metadata/wheel_absence.py
tests/malware_analyzer/pypi/test_wheel_absence.py

`wheel_absence.py` now include inspector links regardless of if they are reachable or not in its detail information, along with a boolean for each identifying if it is reachable.
Recently team members have had some troubles accessing PyPI inspector, and as a result observing that after running Macaron analysis, the inspector links are not provided in the output. To ensure the links are still available in the results, this PR now changes the detail information returned by `wheel_absence.py` to include the inspector links regardless of whether they are reachable or not. It also then include a boolean value identifying if it was reachable by that Macaron instance.

fix: include inspector links with information on if they are reachable.

---

docs/source/pages/cli_usage/command_analyze.rst
docs/source/pages/tutorials/detect_malicious_package.rst

This PR follows on from #965 by including a write-up explanation of how to use the source code analysis component of Macaron.
A source code analysis subsection has been added to `detect_malicious_package.rst` explaining at a high level how to use the source code analysis capability introduced by #965, in line with the included components into the tutorial's integration test (`tests/integration/cases/django_with_dep_resolution_virtual_env_as_input`) for source code analysis.

docs: include source code analysis subsection in malicious package tutorial

---

src/macaron/slsa_analyzer/package_registry/pypi_registry.py

This PR improves the functionality of the pypi_registry.py by enhancing the reliability of requests made to the PyPI registry.
- Replaced the dynamic URL construction with a hardcoded PyPI project URL to avoid issues with incorrect joins and ensure consistent access

fix(pypi): update get_maintainers_of_package to avoid request blocking

---

.flake8
.pre-commit-config.yaml
pyproject.toml
tests/test_util.py

Add `flake8-print` plugin to enforce detection of `print` statements in code, and update the pre-commit hooks.
This PR introduces the [`flake8-print`](https://pypi.org/project/flake8-print/) plugin to the codebase via the pre-commit configuration. This plugin flags any usage of the `print` function, which is generally discouraged in production code in favor of proper logging.
Changes:
- Added `flake8-print` to the list of pre-commit hooks.
- Updated `pre-commit` configuration to include the plugin.
- Added `per-file-ignores` for test scripts where `print` statements are used legitimately (e.g., for test output).

build: add flake8-print plugin and update pre-commit

---

src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py

This is a PR to handle issues experience with malware heuristic dependencies (i.e. the `depends_on` functionality), which #1133 is attempting to handle. This PR temporarily solves these issues whilst that PR is still in development.
Modified the `_should_skip` method of `DetectMaliciousMetadataCheck` so that multiple entries in `depends_on` are handled as expected.

chore: fix heuristic dependency handling temporarily

---

src/macaron/malware_analyzer/pypi_heuristics/heuristics.py
src/macaron/malware_analyzer/pypi_heuristics/metadata/similar_projects.py
src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py
src/macaron/slsa_analyzer/package_registry/pypi_registry.py
tests/malware_analyzer/pypi/test_similar_projects.py

This PR adds a new heuristic analyzer called `SimilarProjectAnalyzer`. It checks whether a PyPI package has a similar file/folder structure to other packages maintained by the same user. This helps in identifying potentially malicious packages that replicate existing structures.
- Created a new analyzer: `SimilarProjectAnalyzer`.
- The analyzer fetches the list of maintainers of the target package and retrieves other packages published by those maintainers.
- For each package, it computes a normalized structure hash from its sdist tarball and compares it to the structure hash of the target package.
- If any match is found, the heuristic fails, flagging potential structural duplication.
- Added this analyzer to the `heuristics.py` registry.
- Modified `detect_malicious_metadata_check.py` …

feat(heuristics): add SimilarProjectAnalyzer to detect structural similarity across packages from same maintainer

---

src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py

With the existing `malware_medium_confidence_3` which was introduced with the `FakeEmailAnalyzer`, some false positives were observed. This PR changes this rule by adding in further heuristics to reduce false positives. 
The rationale for including the `FakeEmailAnalyzer` in a rule is to increase the confidence that a maintainer is suspicious and may have released a malicious package. To make use of this, the rule `quickUndetailed`, which looks for a non-descriptive (no links) package with a recently-joined maintainer, along with `SimilarProjects` and either `OneRelease` or `HighReleaseFrequency` have been included along with the `FakeEmailAnalyzer`. This is representative of a suspicious package, combined with indicators of a suspicious maintainer. 
This was tested against the observed …

chore: change rules for fake email analyzer to reduce FPs

---

src/macaron/malware_analyzer/pypi_heuristics/metadata/similar_projects.py

This PR addresses a bug in the `SimilarProjectAnalyzer` where exceptions were not properly handled. Additionally, it improves efficiency by ensuring that the `SIMILAR_PROJECTS` heuristic only runs when most other heuristics have failed.
The main changes in this PR are:
1. Exception handling: The bug where exceptions were not properly handled in the `SimilarProjectAnalyzer` has been fixed. See a [this CI error](https://github.com/oracle/macaron/actions/runs/16898732099/job/47873695334?pr=1145#step:8:7337).
2. Efficiency improvement: To address performance concerns, the `SIMILAR_PROJECTS` heuristic now only runs when the majority of other heuristics have failed. This is achieved by adding those heuristics to the `depends_on` list.
3. Additionally, a TODO has been added to for this known …

chore: fix a bug in SimilarProjectAnalyzer

---

.github/workflows/build_base_image.yaml
docker/Dockerfile.base

This PR updates the Souffle version in the base image to 2.5 and addresses a build failure issue by downloading and extracting JDK 17 as a tarball.
- Souffle version update: The base image has been updated to use Souffle version 2.5. This update ensures compatibility with the latest features and improvements of Souffle.
- JDK 17 installation: To resolve a build failure issue, JDK 17 is now downloaded and extracted as a tarball. This replaces the previous JDK version installation as an rpm package.

chore(deps): update Souffle in base image to version 2.5

---

src/macaron/malware_analyzer/pypi_heuristics/sourcecode/pypi_sourcecode_analyzer.py
tests/malware_analyzer/pypi/test_pypi_sourcecode_analyzer.py

To address #1129, this PR modifies some configurations for Semgrep in `pypi_sourcecode_analyzer` to allow unit tests to run completely offline. 
The following command line arguments are added to prevent operations in Semgrep that make network connections:
- [Semgrep metrics](https://semgrep.dev/docs/metrics) are disabled, as these make network connections to `metrics.semgrep.dev:443`.
- The [version check](https://semgrep.dev/docs/cli-reference) is disabled, as this makes a connection to Semgrep servers to see if the latest version is run. 
After adding this, there are still network connections made by `semgrep scan --validate` to pull in linting rules. Currently, there is no way to run this without pulling in the rules using that remote connection (a feature request for this is …

test: resolve bugs in sourcecode analyzer to allow unit tests to run offline

---

.github/workflows/build_base_image.yaml
docker/Dockerfile.base
docker/Dockerfile.final

This PR updates the base Docker image to incorporate the latest dependencies that fix known vulnerabilities.
- Python has been upgraded to 3.11.13 for enhanced security.
- JDK has been removed because the current version, `17.0.12` has known vulnerabilities and we don't really use Java anymore after [this PR](https://github.com/oracle/macaron/pull/1155) was merged. It can be re-added as needed for specific use cases.
- The base ol9-slim image has been updated to the latest version.

chore(deps): update the base Docker image

---

.github/workflows/codeql-analysis.yaml

This PR adds the `actions` scanner to the CodeQL configuration, which has been recently added to the supported languages.
It also removes `javascript` which was originally added for partial analysis of GitHub Actions. This is not required anymore.
See the latest set of supported languages [here](https://docs.github.com/en/code-security/code-scanning/creating-an-advanced-setup-for-code-scanning/customizing-your-advanced-setup-for-code-scanning#changing-the-languages-that-are-analyzed).

ci: add actions to CodeQL languages

---

src/macaron/config/defaults.ini
src/macaron/repo_verifier/repo_verifier.py
src/macaron/repo_verifier/repo_verifier_base.py
src/macaron/repo_verifier/repo_verifier_gradle.py
src/macaron/repo_verifier/repo_verifier_maven.py
src/macaron/slsa_analyzer/build_tool/base_build_tool.py
src/macaron/slsa_analyzer/build_tool/docker.py
src/macaron/slsa_analyzer/build_tool/go.py
src/macaron/slsa_analyzer/build_tool/gradle.py
src/macaron/slsa_analyzer/build_tool/maven.py
src/macaron/slsa_analyzer/build_tool/npm.py
src/macaron/slsa_analyzer/build_tool/pip.py
src/macaron/slsa_analyzer/build_tool/poetry.py
src/macaron/slsa_analyzer/build_tool/yarn.py
tests/integration/cases/IntellectualSites_Arkitektonika-Client/policy.dl
tests/integration/cases/IntellectualSites_Arkitektonika-Client/test.yaml
tests/integration/cases/fnproject_fdk-java/policy.dl
tests/integration/cases/fnproject_fdk-java/test.yaml
tests/integration/cases/timyarkov_multibuild_test_maven/configuration.ini
tests/integration/cases/timyarkov_multibuild_test_maven/test.yaml
tests/repo_verifier/mock_repos/gradle_repos/fail_groovy/tests/build.gradle
tests/repo_verifier/mock_repos/gradle_repos/fail_kotlin/tests/build.gradle.kts
tests/repo_verifier/mock_repos/gradle_repos/fail_properties/tests/gradle.properties
tests/repo_verifier/mock_repos/gradle_repos/pass_groovy/build.gradle
tests/repo_verifier/mock_repos/gradle_repos/pass_kotlin/build.gradle.kts
tests/repo_verifier/mock_repos/gradle_repos/pass_properties/gradle.properties
tests/repo_verifier/mock_repos/maven_repos/fail_pom/tests/pom.xml
tests/repo_verifier/mock_repos/maven_repos/pass_pom/pom.xml
tests/repo_verifier/test_repo_verifier.py

Refactored the build tool detection logic by reusing the repo verifier’s path filtering approach. This change ensures that paths that are likely used for testing are excluded during the build tool detection process. Additionally, this PR adds an integration test for a project that uses Maven, with Gradle used as an example to demonstrate the filtering mechanism.
- Refactored build tool detection reusing the repo verifier’s logic for filtering paths that are likely used for testing, improving the reliability of build tool detection by excluding unnecessary paths.
- Integration test: added an integration test for a project that uses Maven as the build tool. The test also demonstrates how Gradle is treated as an example and excluded from detection if it falls under test-related or example …

fix: improve build tool detection

---

src/macaron/malware_analyzer/pypi_heuristics/base_analyzer.py
src/macaron/malware_analyzer/pypi_heuristics/metadata/type_stub_file.py
src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py
tests/integration/cases/pypi_ibm-agent-analytics-common/policy.dl
tests/integration/cases/pypi_ibm-agent-analytics-common/test.yaml
tests/malware_analyzer/pypi/test_type_stub_file.py

This PR addresses a bug related to the uncaught `SourceCodeError` exception in the PyPI type stub file analyzer. An additional integration test has been added to ensure correct handling for Python packages distributed only as wheels.
- Bug fix: handles situations where source code files cannot be downloaded. In this case, the `TypeStubFileAnalyzer` fails, instead of raising an exception.
- A TODO comment is added to note that `.pyi` stub files may reside in both `sdist` and `wheel` distributions.
- Unit test updated.
- Added a new integration test case and a policy for packages only distributed as `wheels` and not as `sdists` (e.g., `ibm-agent-analytics-common`).

chore: fix a bug for uncaught SourceCodeError exception

---

src/macaron/config/defaults.ini
tests/slsa_analyzer/package_registry/test_maven_central_registry.py

This PR witches to use [Central Search](https://central.sonatype.com/solrsearch/select) for Maven artifacts instead of search.maven.org.
Central Search appears to be more stable based on [published operational statistics](https://status.maven.org/). The Central Search API is compatible with our current integration and requires minimal changes. This PR also updates the related unit test.

chore: switch to using Central Search for Maven artifacts

---

src/macaron/config/defaults.ini
src/macaron/malware_analyzer/README.md
src/macaron/resources/pypi_malware_rules/obfuscation.yaml
tests/malware_analyzer/pypi/resources/sourcecode_samples/obfuscation/excessive_spacing.py
tests/malware_analyzer/pypi/resources/sourcecode_samples/obfuscation/expected_results.json

Many false positives were being triggered from the introduction of the excessive whitespace obfuscation rule in #1086. This is due to a lack of specificity in the rule. This PR resolves that change by considering the key syntax of using `;` that is the primary malicious indicator for this method of obfuscation.
The rule originally considered any amount of excessive spacing (50 or more) before encountering code. Whitespaces here includes newline characters, and with Semgrep running regex pattern matching in multiline matching mode, this would trigger against code lines where a long line of code was broken across multiple lines like:
```
<indentation>                                             foo(arg1, another_foo(arg_2), 
arg3_on_other_line)
```
Due to differences in formatting in code …

chore: reduce FPs in whitespace PR by considering ; statement

---

docs/source/pages/tutorials/detect_malicious_package.rst
docs/source/pages/tutorials/provenance.rst
src/macaron/config/defaults.ini
src/macaron/malware_analyzer/pypi_heuristics/sourcecode/suspicious_setup.py
src/macaron/provenance/provenance_finder.py
src/macaron/provenance/provenance_verifier.py
src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py
src/macaron/slsa_analyzer/git_service/api_client.py
src/macaron/slsa_analyzer/package_registry/maven_central_registry.py
src/macaron/slsa_analyzer/package_registry/pypi_registry.py
src/macaron/util.py
tests/integration/cases/django_with_dep_resolution_virtual_env_as_input/config.ini
tests/integration/cases/ossf_scorecard/config.ini

Changes the behaviour and way `max_download_size` is accessed with respect to package source code analysis.
This PR makes two main changes. It moves the `max_download_size` configuration from `slsa.verifier` to `downloads` in `defaults.ini`, and adds a new function `can_download_file` that is used to check first if the source code of a package can be downloaded before acting upon this information. This is useful in `DetectMaliciousMetadataCheck.analyze_source` to ensure that a `HeuristicAnalyzerValueError` is not raised, and a subsequent `UNKNOWN` result is not returned if the file limit stops the source code from being downloaded.
This PR also updates the tutorial documentation to describe the changes needed to ensure some larger packages are downloaded when analyzing the source code.

chore: improve max download restrictions for malicious metadata tutorial

---

Makefile
docker/Dockerfile.base
docs/source/pages/supported_technologies/index.rst
docs/source/pages/tutorials/detect_malicious_package.rst
docs/source/pages/using.rst
pyproject.toml

This PR ensures Python `3.11.13` is used to mitigate the vulnerability identified in [GHSA-4xh5-x5gv-qwph](https://github.com/advisories/GHSA-4xh5-x5gv-qwph), as this version is not affected by the CVE.
- Explicitly ensure Python `3.11.13` is used to avoid the vulnerability associated with `GHSA-4xh5-x5gv-qwph`. Since Python `3.11.13` is not vulnerable, the changes are intended to avoid unnecessary issues related to the advisory.
- A comment has been added to ignore the GHSA advisory for now, with a note to remove this once a new version of pip is released to address the CVE.
Related links:
- https://github.com/pypa/pip/issues/13607
- Our CI failed run: https://github.com/oracle/macaron/actions/runs/18145715888/job/51646824227

fix: ensure Python 3.11.13 is used to address GHSA-4xh5-x5gv-qwph
