oracle/macaron

.github/workflows/codeql-analysis.yaml

chore: enable CodeQL for Go

---

.github/workflows/release.yaml

chore(deps): fix the checkout action semantic version

---

.github/workflows/codeql-analysis.yaml

ci: remove CodeQL Python version from matrix

---

README.md

Signed-off-by: sophie-bates <sophie.bates@oracle.com>

docs: add a reference to checks documentation in the main README

---

src/macaron/code_analyzer/call_graph.py
src/macaron/output_reporter/results.py

chore: fix code documentation on TypeVar variables that make Sphinx build fails (#58)

---

.github/workflows/release.yaml

chore(deps): update SLSA GitHub Generator Action to 1.4.0

---

README.md

chore: update README.md relating to GH_TOKEN environment variable

---

THIRD_PARTY_LICENSES.txt

chore: add THIRD_PARTY_LICENSES.txt

---

src/macaron/dependency_analyzer/cyclonedx.py
src/macaron/dependency_analyzer/dependency_resolver.py
tests/dependency_analyzer/cyclonedx/__snapshots__/test_cyclonedx.ambr
tests/dependency_analyzer/cyclonedx/resources/bom_multi_versions.json
tests/dependency_analyzer/cyclonedx/resources/bom_no_group.json
tests/dependency_analyzer/cyclonedx/resources/bom_no_version.json
tests/dependency_analyzer/cyclonedx/test_cyclonedx.py

fix: allow BOM component version and group be empty

---

THIRD_PARTY_LICENSES.txt

chore: update THIRD_PARTY_LICENSES.txt to prepare for v0.1.0

---

src/macaron/dependency_analyzer/cyclonedx.py
src/macaron/dependency_analyzer/dependency_resolver.py
tests/dependency_analyzer/cyclonedx/__snapshots__/test_cyclonedx.ambr
tests/dependency_analyzer/cyclonedx/resources/bom_no_group.json
tests/dependency_analyzer/cyclonedx/resources/bom_no_version.json

fix: initialize all DependencyInfo attributes

---

scripts/release_scripts/run_macaron.sh

chore: turn off py warnings in prod

---

scripts/dev_scripts/integration_tests_docker.sh
scripts/release_scripts/run_macaron.sh

chore: add SBOM support for running the Docker image

---

src/macaron/code_analyzer/call_graph.py

This PR improves the BFS implementation in call graph construction using [`collections.deque`](https://docs.python.org/3/library/collections.html?highlight=deque#collections.deque) which has O(1) time complexity for adding/removing elements from either end of the queue.

chore: use deque in BFS to improve performance

---

README.md
scripts/dev_scripts/integration_tests.sh
scripts/dev_scripts/integration_tests_docker.sh
scripts/release_scripts/run_macaron.sh
src/macaron/__main__.py
src/macaron/config/global_config.py

chore: pass GITHUB_TOKEN from environment variable instead of cmd arg (#199)

---

docs/README.md
docs/source/pages/apidoc/macaron.dependency_analyzer.rst
docs/source/pages/apidoc/macaron.output_reporter.rst
docs/source/pages/apidoc/macaron.policy_engine.rst
docs/source/pages/apidoc/macaron.rst
docs/source/pages/apidoc/macaron.slsa_analyzer.build_tool.rst
docs/source/pages/apidoc/macaron.slsa_analyzer.checks.rst
docs/source/pages/apidoc/macaron.slsa_analyzer.rst

docs: update Sphinx's API documentation

---

.github/workflows/_build_docker.yaml

build: remove login step because macaron-base is public

---

src/macaron/resources/init.gradle

fix: do not skip rootProject in Gradle dependency resolution

---

src/macaron/__main__.py
tests/test_main.py

feat: add command-line flag for version

---

docs/README.md

chore: update README in the docs directory

---

docs/source/pages/using.rst

chore: fix broken SBOM example link in Sphinx documentation

---

docker/Dockerfile.base
docker/Dockerfile.final

chore: upgrade to python 3.11.4

---

.pre-commit-config.yaml
src/macaron/config/defaults.py
src/macaron/config/target_config.py
src/macaron/database/rfc3339_datetime.py
src/macaron/database/table_definitions.py
src/macaron/dependency_analyzer/cyclonedx.py
src/macaron/dependency_analyzer/java_repo_finder.py
src/macaron/output_reporter/reporter.py
src/macaron/output_reporter/results.py
src/macaron/policy_engine/souffle.py
src/macaron/slsa_analyzer/analyzer.py
src/macaron/slsa_analyzer/checks/base_check.py
src/macaron/slsa_analyzer/provenance/expectations/cue/cue_validator.py
src/macaron/slsa_analyzer/provenance/expectations/expectation.py
src/macaron/slsa_analyzer/provenance/expectations/expectation_registry.py

style: enforce py311 in pyupgrade and add the adjustments

---

Makefile

See https://github.com/ishepard/pydriller/issues/280

chore(deps): ignore GHSA-pr76-5cm5-w9cj until PyDriller updates GitPython

---

SECURITY.md

This PR adds the change from #450 so that it is included in the upcoming release.

docs: adjust SECURITY.md

---

src/macaron/config/defaults.ini
src/macaron/slsa_analyzer/git_service/api_client.py

Closes #392.
I am adding this because I encountered this issue again today in [this job](https://github.com/oracle/macaron/actions/runs/6269369980/job/17025702477#step:8:1282).
I am not sure if the PR type should be `feat` though. Let me know what you think.

feat: add download timeout config

---

scripts/dev_scripts/integration_tests_docker.sh

Adds one additional docker integration test case for the VSA generation feature.

test: add docker integration test for VSA generation feature

---

.pre-commit-config.yaml
src/macaron/parsers/github_workflow_model.py
src/macaron/slsa_analyzer/analyze_context.py
src/macaron/slsa_analyzer/checks/build_as_code_check.py
src/macaron/slsa_analyzer/checks/build_script_check.py
src/macaron/slsa_analyzer/checks/build_service_check.py
tests/parsers/bashparser/test_bashparser.py

This PR updates the `pre-commit` hooks and fixes `black` formatting issues caught after the update.
I will update the `flake8` hooks separately as a few changes are required after the update.

chore(deps-dev): update pre-commit hooks

---

CONTRIBUTING.md
tests/integration/README.md
tests/integration/cases/apache_maven_cyclonedx_sbom_tutorial/test.yaml
tests/integration/cases/apache_maven_sbom_no_repo_tutorial/test.yaml
tests/integration/cases/django_with_dep_resolution_virtual_env_as_input/test.yaml
tests/integration/cases/example_maven_app_automatic_dep_resolution_tutorial/test.yaml

chore: add a new tag for tutorial integration tests

---

src/macaron/slsa_analyzer/build_tool/gradle.py
tests/slsa_analyzer/build_tool/test_gradle.py

chore: remove get group id using gradlew logic

---

.gitignore

test: add repo finder test repo directory to .gitignore

---

Makefile

This cleans up some redundant lines in the souffle install script for Ubuntu

chore: remove redundant lines in ubuntu souffle install

---

.github/pull_request_template.md

This PR updates the pull request template to improve the clarity and structure of the information provided. Note that the sections in this template are optional and can be skipped if not necessary by the contributor. But they give an idea of what we expect in the PR.

chore: improve the PR template

---

THIRD_PARTY_LICENSES.txt

This Pull Request updates the [THIRD_PARTY_LICENSES.txt](./THIRD_PARTY_LICENSES.txt) file for the upcoming release v0.17.0

chore: update third party license for release v0.17.0

---

src/macaron/slsa_analyzer/checks/build_as_code_check.py
src/macaron/slsa_analyzer/checks/detect_malicious_metadata_check.py

This PR improves some of the check descriptions that are automatically displayed in the terminal.

docs: improve the check descriptions automatically shown in terminal

---

docs/source/pages/installation.rst

This closes #1192 by updating the download URL
URL updated to match actual GitHub format

fix(docs): path of script download example
